"""MONOTONE_PREREG.md analysis. Written before any arm finished.

    python3 -m mapformer.analyze_monotone            (from /home/prashr)
Writes MONOTONE_RAW.md and MONOTONE_RAW.json. Verdict rules are the pre-registration's.
"""
from __future__ import annotations

import json

import numpy as np
import torch

from mapformer.ckpt_guard import REPO, load_checkpoint, compare_checkpoints
from mapformer.stats_guard import paired, rule9, table, loss_matched, interaction

SEEDS = list(range(12))
REC = REPO / "runs/monotone/recency"
TOR = REPO / "runs/monotone/torus"
REC_ARMS = ["VanillaEM_P0_r4", "EM_P0_Abs_r4", "Signed_r4", "Abs_r4", "SRoPEGen", "SRoPEGen_Abs"]
TOR_ARMS = ["SRoPEGen", "SRoPEGen_Abs"]


def load_recency():
    rows = {}
    for a in REC_ARMS:
        for s in SEEDS:
            d = REC / f"{a}_s{s}"
            r = json.load(open(d / f"{a}_recency.json"))
            ck = load_checkpoint(d / f"{a}_recency.pt")
            rows[(a, s)] = {"acc1024": r["1024"]["acc"], "acc2048": r["2048"]["acc"],
                            "loss": float(ck.losses[-1])}
    return rows


def load_torus():
    ev = json.load(open(REPO / "_MONOTONE_TORUS.json"))
    rows = {}
    for a in TOR_ARMS:
        for s in SEEDS:
            ck = load_checkpoint(TOR / "p0" / f"{a}_s{s}" / f"{a}.pt")
            r = {"loss": float(ck.losses[-1])}
            for T in (128, 512, 1024):
                hit = [x for x in ev[f"0.0|{a}|{T}"] if x[0] == s]
                r[f"acc{T}"] = float(hit[0][1])
            rows[(a, s)] = r
    return rows


def col(rows, a, k):
    return {s: rows[(a, s)][k] for s in SEEDS}


def ceiling_len(rows, a, b):
    m = lambda x: np.mean(list(col(rows, x, "acc1024").values()))
    return "acc2048" if (m(a) >= 0.99 and m(b) >= 0.99) else "acc1024"


@torch.no_grad()
def min_increments():
    """M-C1: most negative per-channel increment each checkpoint produces on random tokens."""
    from mapformer.train_variant import VARIANT_MAP
    out = {}
    g = torch.Generator().manual_seed(123)
    specs = [(REC, a, "{a}_s{s}/{a}_recency.pt") for a in REC_ARMS] \
          + [(TOR / "p0", a, "{a}_s{s}/{a}.pt") for a in TOR_ARMS]
    for base, a, pat in specs:
        mins = []
        for s in SEEDS:
            ck = load_checkpoint(base / pat.format(a=a, s=s))
            cfg = ck.config
            with torch.random.fork_rng(devices=[]):
                m = VARIANT_MAP[a](vocab_size=cfg["vocab_size"], d_model=cfg.get("d_model", 128),
                                   n_heads=cfg.get("n_heads", 2), n_layers=cfg.get("n_layers", 1),
                                   grid_size=cfg.get("grid_size", 64))
            m.load_state_dict(ck.state); m.eval()
            x = torch.randint(0, cfg["vocab_size"], (8, 512), generator=g)
            e = m.token_emb(x)
            if hasattr(m, "angle"):
                ang = m.angle
                w = ang.proj(e)
                if ang.conv is not None:
                    w = ang.conv(w)
                if ang.gate is not None:
                    w = w * torch.sigmoid(ang.gate(e))
                if type(ang).__name__ == "_MonotoneSelectiveAngle":
                    w = w.abs()
                inc = ang.log_temp.exp() * w
                # cross-check that this IS the increment the model accumulates
                th = ang(e).view(*inc.shape)
                assert torch.allclose(torch.cumsum(inc, 1), th, rtol=1e-4, atol=1e-4), a
            else:
                inc = m.action_to_lie(e)
            mins.append(float(inc.min()))
        out[f"{base.name}/{a}"] = mins
    return out


def rewind_route(dev="cuda:0"):
    from mapformer.probe_anatomy import anatomy
    from mapformer.probe_rewind import load_model
    out = {}
    for a in ["VanillaEM_P0_r4", "EM_P0_Abs_r4"]:
        fr, nsol = {}, {}
        for s in SEEDS:
            m, ck, env = load_model(REC / f"{a}_s{s}" / f"{a}_recency.pt", a)
            an = anatomy(m, env, s, device=dev)
            S, S0 = np.array(an["sel"]), np.array(an["sel0"])
            M, M0 = np.array(an["selmin"]), np.array(an["selmin0"])
            solved = [k for k in range(8, 65) if an["n"][k - 1] and an["acc"][k - 1] >= 0.9]
            nsol[s] = len(solved)
            if solved:
                fr[s] = float(np.mean([max(S[k - 1].max() - S0[k - 1].max(),
                                           M[k - 1].max() - M0[k - 1].max()) >= 0.5 for k in solved]))
        out[a] = {"route_frac": fr, "n_solved": nsol}
    return out


def main():
    L = ["# MONOTONE raw report (MONOTONE_PREREG.md)\n",
         "Generated by `analyze_monotone.py`. Verdict rules are the pre-registration's; "
         "this file prints them mechanically.\n"]
    J = {}

    # --------------------------------------------------------------- manipulation checks
    mc = min_increments(); J["mc1"] = mc
    L += ["## Manipulation checks\n", "M-C1: min per-channel increment on random tokens (all 12 seeds)\n",
          "| checkpoints | min over seeds | max over seeds | pass |", "|---|---|---|---|"]
    mc_ok = True
    for k, v in mc.items():
        constrained = k.endswith("Abs_r4") or k.endswith("_Abs")
        ok = (min(v) >= 0) if constrained else (max(v) < 0)
        mc_ok &= ok
        L.append(f"| {k} | {min(v):+.3e} | {max(v):+.3e} | {'PASS' if ok else 'FAIL'} |")
    rep = []
    for a in ("Signed_r4", "Abs_r4"):
        c = compare_checkpoints(REPO / f"runs/monotone/torus_repro/p0/{a}_s0/{a}.pt",
                                REPO / f"runs/sign/p0/{a}_s0/{a}.pt")
        rep.append(f"{a} s0: tensors compared {c.n_compared}, differing {len(c.differing)}, "
                   f"only-in-A {len(c.only_a)}, only-in-B {len(c.only_b)}, losses equal {c.losses_equal}")
    L += ["", "M-C3 reproduction control (seed 0 retrained vs `runs/sign/p0`):\n", "```", *rep, "```", ""]
    if not mc_ok:
        L.append("**M-C1 FAILED -- no verdict below may be read.**\n")

    # --------------------------------------------------------------- recency
    R = load_recency()
    L += ["## Recency, per arm (n=12)\n", "| arm | acc T=1024 | acc T=2048 | final loss |", "|---|---|---|---|"]
    for a in REC_ARMS:
        A = np.array(list(col(R, a, "acc1024").values())); B = np.array(list(col(R, a, "acc2048").values()))
        Lo = np.array(list(col(R, a, "loss").values()))
        L.append(f"| {a} | {A.mean():.3f} +/- {A.std(ddof=1):.3f} | {B.mean():.3f} +/- {B.std(ddof=1):.3f} | {Lo.mean():.3f} |")

    p1 = paired(col(R, "EM_P0_Abs_r4", "acc1024"), col(R, "VanillaEM_P0_r4", "acc1024"), "P1 EM: Abs - signed, T=1024")
    k2 = ceiling_len(R, "Abs_r4", "Signed_r4")
    p2 = paired(col(R, "Abs_r4", k2), col(R, "Signed_r4", k2), f"P2 WM: Abs - signed, {k2}")
    p3 = interaction(p1, p2, "P3 interaction P1 - P2", paired=True)
    kq = ceiling_len(R, "SRoPEGen_Abs", "SRoPEGen")
    q2 = paired(col(R, "SRoPEGen_Abs", kq), col(R, "SRoPEGen", kq), f"Q2 SRoPE recency: Abs - signed, {kq}")
    p1_2048 = paired(col(R, "EM_P0_Abs_r4", "acc2048"), col(R, "VanillaEM_P0_r4", "acc2048"), "EM: Abs - signed, T=2048 (secondary)")
    acc = {a: col(R, a, "acc1024") for a in REC_ARMS}; los = {a: col(R, a, "loss") for a in REC_ARMS}
    p1lm, r9rec = loss_matched(acc, los, "EM_P0_Abs_r4", "VanillaEM_P0_r4", label="P1 loss-matched (reported, not read)")
    L += ["", "## Recency contrasts\n", table([p1, p1_2048, p1lm, p2, q2]), "", str(p3), "", str(r9rec), ""]

    rr = rewind_route(); J["route"] = rr
    L += ["## P4: route of solved cells (acc >= 0.9, k >= 8)\n",
          "| arm | seeds with solved cells | mean solved cells / seed | mean rewind-route fraction |", "|---|---|---|---|"]
    for a, v in rr.items():
        fr = list(v["route_frac"].values())
        L.append(f"| {a} | {len(fr)}/12 | {np.mean(list(v['n_solved'].values())):.1f} | "
                 f"{(np.mean(fr) if fr else float('nan')):.3f} |")
    e2_route = np.mean(list(rr["EM_P0_Abs_r4"]["route_frac"].values())) if rr["EM_P0_Abs_r4"]["route_frac"] else float("nan")

    neg = lambda c: c.verdict == "DETECTABLE" and c.delta < 0
    pos = lambda c: c.verdict == "DETECTABLE" and c.delta > 0
    if neg(p1) and p3.verdict == "DETECTABLE" and p3.delta < 0:
        v1 = "SUBTRACTION NEEDED"
    elif pos(p1):
        v1 = "MONOTONE HELPS EM"
    elif (not neg(p1)) and p1.mde <= 0.15 and e2_route >= 0.5:
        v1 = "WRAP SUBSTITUTES"
    else:
        v1 = "UNRESOLVED"
    L += ["", f"**Experiment 1 verdict: {v1}**\n"]

    # --------------------------------------------------------------- torus
    Tt = load_torus()
    L += ["## Torus, per arm (n=12)\n", "| arm | T=128 | T=512 | T=1024 | final loss |", "|---|---|---|---|---|"]
    for a in TOR_ARMS:
        cells = [np.array(list(col(Tt, a, f"acc{T}").values())) for T in (128, 512, 1024)]
        Lo = np.array(list(col(Tt, a, "loss").values()))
        L.append(f"| {a} | " + " | ".join(f"{c.mean():.3f} +/- {c.std(ddof=1):.3f}" for c in cells) + f" | {Lo.mean():.4f} |")
    cs = []
    for T in (128, 512, 1024):
        raw = paired(col(Tt, "SRoPEGen_Abs", f"acc{T}"), col(Tt, "SRoPEGen", f"acc{T}"), f"SRoPE torus Abs - signed, T={T}, raw")
        lm, r9 = loss_matched({a: col(Tt, a, f"acc{T}") for a in TOR_ARMS}, {a: col(Tt, a, "loss") for a in TOR_ARMS},
                              "SRoPEGen_Abs", "SRoPEGen", label=f"SRoPE torus Abs - signed, T={T}, loss-matched")
        cs += [raw, lm]
        L.append(f"- T={T}: {r9}")
        if T == 1024:
            q1raw, q1 = raw, lm
    L += ["", "## Torus contrasts (Q1 = T=1024 loss-matched)\n", table(cs), ""]
    q3 = interaction(q1raw, q2, "Q3 crossover: torus(raw, T=1024) - recency", paired=False)
    L += [str(q3), ""]
    q1_fals = (not neg(q1)) and q1.mde <= 0.10
    L += ["**Experiment 2 predictions**\n",
          f"- Q1 detectably negative: {'MET' if neg(q1) else ('FALSIFIED' if q1_fals else 'not met, not falsified (MDE > 0.10)')}",
          f"- Q2 not detectably negative: {'FALSIFIED' if neg(q2) else 'MET'}",
          f"- Q3 detectably negative: {'MET' if (q3.verdict == 'DETECTABLE' and q3.delta < 0) else 'not met'}", ""]

    # --------------------------------------------------------------- exploratory
    try:
        sg = json.load(open(REPO / "_SIGN_RAW.json"))
        g = lambda a: {x[0]: x[1] for x in sg[f"0.0|{a}|1024"]}
        mf = paired(g("Abs_r4"), g("Signed_r4"), "MapFormer-WM torus Abs - signed, T=1024, raw (stored)")
        L += ["## Exploratory (not a verdict)\n", table([mf, q1raw]), "",
              str(interaction(q1raw, mf, "SRoPE sign cost - MapFormer sign cost (unpaired; licensed only if M-C3 is bitwise)")), ""]
    except Exception as ex:  # noqa: BLE001
        L.append(f"exploratory comparison skipped: {ex}")

    J.update(recency={f"{a}|{s}": R[(a, s)] for a, s in R}, torus={f"{a}|{s}": Tt[(a, s)] for a, s in Tt},
             verdict1=v1)
    open(REPO / "MONOTONE_RAW.md", "w").write("\n".join(L) + "\n")
    json.dump(J, open(REPO / "MONOTONE_RAW.json", "w"), indent=1)
    print("\n".join(L))


if __name__ == "__main__":
    main()
