"""Continuous 2D navigation on a torus — Cueva/Wei/Sorscher-style env.

State: (x, y, θ) on a torus [0, size)² × [-π, π).
Action: (v, ω) — translational + angular velocity.
Noise: Gaussian on both v and ω (process / proprioceptive noise type 2).
Observation: DoG-of-position place-cell vector at the current location.

Loss target: predict the place-cell firing at each timestep. No "revisit"
concept — the target is a deterministic smooth function of position, so
every timestep contributes signal.

This is the InEKF use case in its cleanest form:
  - Continuous state with continuous noise (Kalman's home turf)
  - DoG place-cell targets satisfy Sorscher/Ganguli's third hex condition
  - Path integration is the dominant problem (random velocities → drift)
  - Compatible with Level 1.5's existing SO(2) wrap on θ (Scope A)

Compatible with our cached-buffer pattern: pre-generate trajectories once,
store as tensors, sample batches.
"""

from __future__ import annotations

import math
import os
import hashlib
import pickle
import time

import numpy as np
import torch


class ContinuousNav2D:
    """Continuous-state 2D navigation env on a torus.

    Trajectories are generated by random velocity commands with Gaussian
    noise on each step. Observations are DoG place-cell vectors at each
    position. There is no goal and no reward — pure self-supervised
    map-learning task.
    """

    def __init__(
        self,
        size: float = 64.0,
        n_place_cells: int = 256,
        sigma_E: float = 1.5,
        sigma_I: float = 3.0,
        v_mean: float = 0.7,
        v_std: float = 0.3,
        omega_std: float = 0.5,
        v_noise_std: float = 0.0,
        omega_noise_std: float = 0.0,
        dt: float = 1.0,
        seed: int | None = None,
    ):
        """
        Args:
            size: torus side length (cells)
            n_place_cells: place-cell count (must be a perfect square)
            sigma_E, sigma_I: DoG kernel widths (cells)
            v_mean, v_std: base velocity policy (translational, cells/dt)
            omega_std: base angular velocity policy (rad/dt)
            v_noise_std, omega_noise_std: Gaussian process noise on
                executed velocity (added to commanded; this is what the
                model will need to robustly path-integrate around)
            dt: time step (cells/unit and rad/unit)
            seed: RNG seed for the env (separate from numpy global)
        """
        self.size = size
        self.n_place_cells = n_place_cells
        self.sigma_E = sigma_E
        self.sigma_I = sigma_I
        self.v_mean = v_mean
        self.v_std = v_std
        self.omega_std = omega_std
        self.v_noise_std = v_noise_std
        self.omega_noise_std = omega_noise_std
        self.dt = dt
        self.seed = seed

        # Place-cell centres: regular grid on the torus
        side = int(round(n_place_cells ** 0.5))
        assert side * side == n_place_cells, (
            f"n_place_cells ({n_place_cells}) must be a perfect square"
        )
        spacing = size / side
        cs = np.arange(side, dtype=np.float32) * spacing + spacing / 2.0
        cx, cy = np.meshgrid(cs, cs, indexing="ij")
        self.place_centers = np.stack([cx.flatten(), cy.flatten()], axis=-1)  # (n_pc, 2)

        # For shape compatibility with downstream code that expects an
        # integer-vocab notion of "obs". Continuous env has no vocab; we
        # report place-cell dim instead.
        self.unified_vocab_size = n_place_cells  # informational only
        self.action_dim = 2
        self.obs_dim = n_place_cells

    def _torus_dist2(self, p: np.ndarray, c: np.ndarray) -> np.ndarray:
        """Squared torus distance from positions p (..., 2) to centres c (n_pc, 2).

        Returns array of shape (..., n_pc).
        """
        d = p[..., None, :] - c[None, ...]                 # (..., n_pc, 2)
        d = (d + self.size / 2.0) % self.size - self.size / 2.0
        return (d * d).sum(-1)

    def dog_targets(self, positions: np.ndarray) -> np.ndarray:
        """positions: (..., 2). Returns (..., n_pc) non-negative DoG targets.

        Uses *normalized* 2D Gaussians (1/σ² prefactor) so the narrower (excitatory)
        peak is taller than the wider (inhibitory). Without this normalization the
        kernel evaluates to zero at the center and is silently uninformative — a
        bug we hit before. ReLU gives the standard "positive bump in centre, zero
        outside" Mexican-hat shape Sorscher's theory needs.
        """
        d2 = self._torus_dist2(positions, self.place_centers)
        gE = (1.0 / (self.sigma_E ** 2)) * np.exp(-d2 / (2.0 * self.sigma_E ** 2))
        gI = (1.0 / (self.sigma_I ** 2)) * np.exp(-d2 / (2.0 * self.sigma_I ** 2))
        return np.maximum(0.0, gE - gI)

    def generate_trajectory(self, n_steps: int = 128, rng: np.random.RandomState | None = None):
        """Roll out a single trajectory.

        Returns:
            actions:        (n_steps, 2)   commanded (v, ω)
            actions_actual: (n_steps, 2)   executed (v, ω) = commanded + Gaussian noise
            positions:      (n_steps, 2)   (x, y) AFTER each step
            headings:       (n_steps,)     θ AFTER each step (radians, in [-π, π))
            obs:            (n_steps, n_pc) DoG place-cell vector at each position
        """
        if rng is None:
            rng = np.random
        # Random initial state
        x = rng.uniform(0.0, self.size)
        y = rng.uniform(0.0, self.size)
        theta = rng.uniform(-math.pi, math.pi)

        actions       = np.zeros((n_steps, 2), dtype=np.float32)
        actions_act   = np.zeros((n_steps, 2), dtype=np.float32)
        positions     = np.zeros((n_steps, 2), dtype=np.float32)
        headings      = np.zeros((n_steps,),    dtype=np.float32)

        for t in range(n_steps):
            # Sample command
            v_cmd     = rng.normal(self.v_mean, self.v_std)
            omega_cmd = rng.normal(0.0,         self.omega_std)
            actions[t, 0] = v_cmd
            actions[t, 1] = omega_cmd

            # Gaussian process noise on executed velocity
            v_act     = v_cmd     + rng.normal(0.0, self.v_noise_std)     if self.v_noise_std > 0     else v_cmd
            omega_act = omega_cmd + rng.normal(0.0, self.omega_noise_std) if self.omega_noise_std > 0 else omega_cmd
            actions_act[t, 0] = v_act
            actions_act[t, 1] = omega_act

            # Update state
            theta = theta + omega_act * self.dt
            theta = (theta + math.pi) % (2 * math.pi) - math.pi
            x = (x + v_act * math.cos(theta) * self.dt) % self.size
            y = (y + v_act * math.sin(theta) * self.dt) % self.size

            positions[t, 0] = x
            positions[t, 1] = y
            headings[t] = theta

        # Compute DoG observations at every position
        obs = self.dog_targets(positions).astype(np.float32)
        return actions, actions_act, positions, headings, obs

    def generate_batch(self, batch_size: int, n_steps: int = 128, rng=None):
        """Returns batched (actions, actions_actual, positions, headings, obs) tensors."""
        if rng is None:
            rng = np.random
        A   = np.zeros((batch_size, n_steps, 2),                    dtype=np.float32)
        Aa  = np.zeros((batch_size, n_steps, 2),                    dtype=np.float32)
        P   = np.zeros((batch_size, n_steps, 2),                    dtype=np.float32)
        H   = np.zeros((batch_size, n_steps),                       dtype=np.float32)
        O   = np.zeros((batch_size, n_steps, self.n_place_cells),   dtype=np.float32)
        for b in range(batch_size):
            a, aa, p, h, o = self.generate_trajectory(n_steps, rng)
            A[b], Aa[b], P[b], H[b], O[b] = a, aa, p, h, o
        return (
            torch.from_numpy(A), torch.from_numpy(Aa),
            torch.from_numpy(P), torch.from_numpy(H),
            torch.from_numpy(O),
        )


class ContinuousNav2D_Cached(ContinuousNav2D):
    """Pre-generated buffer variant — same pattern as MiniGridWorld_Cached.

    On first generate_batch, builds a buffer of N trajectories and caches
    to disk keyed by (env params, n_steps, buffer_size). Subsequent runs
    with the same params load instantly.
    """

    DEFAULT_CACHE_DIR = os.path.expanduser("~/mapformer/runs/_continuous_nav_cache")

    def __init__(self, *args, buffer_size: int = 25_000, cache_dir: str | None = None, **kwargs):
        super().__init__(*args, **kwargs)
        self.buffer_size = buffer_size
        self.cache_dir = cache_dir or self.DEFAULT_CACHE_DIR
        self._built_key = None
        self._buf_A = None   # (N, T, 2)
        self._buf_Aa = None  # (N, T, 2)
        self._buf_P = None   # (N, T, 2)
        self._buf_H = None   # (N, T)
        self._buf_O = None   # (N, T, n_pc)

    def _cache_path(self, n_steps: int) -> str:
        # Buffer is identified by all the env knobs + n_steps + buffer_size
        s = (f"size{self.size}|npc{self.n_place_cells}|sigE{self.sigma_E}|sigI{self.sigma_I}"
             f"|vm{self.v_mean}|vs{self.v_std}|os{self.omega_std}"
             f"|vn{self.v_noise_std}|on{self.omega_noise_std}|dt{self.dt}"
             f"|seed{self.seed}|N{self.buffer_size}|T{n_steps}")
        h = hashlib.sha1(s.encode()).hexdigest()[:12]
        return os.path.join(self.cache_dir, f"buf_{h}.npz")

    def _build_buffer(self, n_steps: int):
        path = self._cache_path(n_steps)
        os.makedirs(self.cache_dir, exist_ok=True)
        if os.path.exists(path):
            d = np.load(path)
            self._buf_A  = d["A"];  self._buf_Aa = d["Aa"]
            self._buf_P  = d["P"];  self._buf_H  = d["H"]
            self._buf_O  = d["O"]
            print(f"[ContinuousNav2D_Cached] Loaded {len(self._buf_A)} trajectories from {path}")
            return

        print(f"[ContinuousNav2D_Cached] Building {self.buffer_size} trajectories of "
              f"{n_steps} steps (cached at {path})...")
        rng = np.random.RandomState(self.seed)
        t0 = time.time()
        N = self.buffer_size
        A  = np.zeros((N, n_steps, 2),                    dtype=np.float32)
        Aa = np.zeros((N, n_steps, 2),                    dtype=np.float32)
        P  = np.zeros((N, n_steps, 2),                    dtype=np.float32)
        H  = np.zeros((N, n_steps),                       dtype=np.float32)
        O  = np.zeros((N, n_steps, self.n_place_cells),   dtype=np.float32)
        for i in range(N):
            a, aa, p, h, o = self.generate_trajectory(n_steps, rng=rng)
            A[i], Aa[i], P[i], H[i], O[i] = a, aa, p, h, o
            if (i + 1) % 5000 == 0:
                rate = (time.time() - t0) / (i + 1) * 1000
                eta = (N - i - 1) * rate / 1000
                print(f"  {i+1:>6d}/{N} ({rate:.2f} ms/traj, ETA {eta:.0f}s)")
        self._buf_A, self._buf_Aa, self._buf_P, self._buf_H, self._buf_O = A, Aa, P, H, O
        np.savez(path, A=A, Aa=Aa, P=P, H=H, O=O)
        print(f"[ContinuousNav2D_Cached] Built in {time.time()-t0:.1f}s; saved.")

    def generate_batch(self, batch_size: int, n_steps: int = 128, rng=None):
        if self._built_key != n_steps:
            self._build_buffer(n_steps)
            self._built_key = n_steps
        idx = np.random.randint(0, self.buffer_size, size=batch_size)
        return (
            torch.from_numpy(self._buf_A [idx]),
            torch.from_numpy(self._buf_Aa[idx]),
            torch.from_numpy(self._buf_P [idx]),
            torch.from_numpy(self._buf_H [idx]),
            torch.from_numpy(self._buf_O [idx]),
        )
