#!/bin/bash
# VanillaNoDrop control: does dropout removal alone (without InEKF correction)
# explain the Level15NoDrop win?
#
# Multi-env held-out, clean + lm200, n=3 seeds each = 6 runs.
# Background: GPU 1 at nice -n 15, sequential, no GPU-busy gate.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

GPU=1
echo "[$(date)] [vanilla-nodrop-ctrl] starting on GPU $GPU"

# Clean (no landmarks)
for seed in 0 1 2; do
    OUT="$REPO/runs/VanillaNoDrop_multienv_clean/seed${seed}"
    CKPT="$OUT/VanillaNoDrop_multienv.pt"
    mkdir -p "$OUT"
    if [ -f "$CKPT" ]; then
        echo "[$(date)] skip clean s${seed} (exists)"
        continue
    fi
    echo "[$(date)] training VanillaNoDrop multi-env clean s${seed}"
    nice -n 15 bash -c "CUDA_VISIBLE_DEVICES=$GPU python3 -u -m mapformer.train_multienv \
        --variant VanillaNoDrop --seed $seed \
        --n-landmarks 0 --n-train-envs 50 --n-test-envs 50 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/VanillaNoDrop_multienv_clean/seed${seed}" \
        > "$LOGS/VanillaNoDrop_multienv_clean_s${seed}.log" 2>&1
done

# LM200 (with landmarks)
for seed in 0 1 2; do
    OUT="$REPO/runs/VanillaNoDrop_multienv/seed${seed}"
    CKPT="$OUT/VanillaNoDrop_multienv.pt"
    mkdir -p "$OUT"
    if [ -f "$CKPT" ]; then
        echo "[$(date)] skip lm200 s${seed} (exists)"
        continue
    fi
    echo "[$(date)] training VanillaNoDrop multi-env lm200 s${seed}"
    nice -n 15 bash -c "CUDA_VISIBLE_DEVICES=$GPU python3 -u -m mapformer.train_multienv \
        --variant VanillaNoDrop --seed $seed \
        --n-landmarks 200 --n-train-envs 50 --n-test-envs 50 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/VanillaNoDrop_multienv/seed${seed}" \
        > "$LOGS/VanillaNoDrop_multienv_s${seed}.log" 2>&1
done

# Aggregate: 4-row comparison table
cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/VANILLANODROP_CONTROL.md" 2>"$LOGS/vanilla_nodrop_eval.err"
import torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

def collect(variant, setting):
    if setting == "clean":
        tmpl = f"mapformer/runs/{variant}_multienv_clean/seed{{s}}/{variant}_multienv.pt"
    else:
        tmpl = f"mapformer/runs/{variant}_multienv/seed{{s}}/{variant}_multienv.pt"
    tr, t128, t512 = [], [], []
    for s in [0, 1, 2]:
        p = Path(tmpl.format(s=s))
        if not p.exists(): continue
        c = torch.load(p, map_location="cpu", weights_only=False)
        if c.get("train_acc") is not None: tr.append(c["train_acc"])
        if c.get("test_acc") is not None: t128.append(c["test_acc"])
        if c.get("test_acc_T2") is not None: t512.append(c["test_acc_T2"])
    return tr, t128, t512

print("# VanillaNoDrop control: is dropout removal enough without InEKF correction?\n")
print("Tests whether the Level15NoDrop win on lm200 reduces to 'remove an")
print("inherited dropout layer.' If VanillaNoDrop ≈ Level15NoDrop, InEKF")
print("correction is redundant once dropout is fixed.\n")

for setting, label in [("lm200", "Multi-env LM200 (with landmarks)"),
                       ("clean", "Multi-env CLEAN (no landmarks)")]:
    print(f"## {label}\n")
    print("| Variant | Train | Held T=128 | Held T=512 OOD |")
    print("|---|---|---|---|")
    for v in ["Vanilla", "VanillaNoDrop", "Level15", "Level15NoDrop"]:
        tr, t128, t512 = collect(v, setting)
        print(f"| **{v}** | {fmt(tr)} | {fmt(t128)} | {fmt(t512)} |")
    print()

print("## Interpretation\n")
print("- **VanillaNoDrop ≈ Level15NoDrop (~0.95+):** dropout was the dominant factor; InEKF correction adds nothing on top of the dropout fix on this task.")
print("- **VanillaNoDrop intermediate (~0.85):** dropout helps both backbones; InEKF still adds independent value.")
print("- **VanillaNoDrop ≈ Vanilla (~0.72):** dropout removal only helps when paired with InEKF correction.\n")
print("*Auto-generated by run_vanilla_nodrop_control.sh*")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add VANILLANODROP_CONTROL.md run_vanilla_nodrop_control.sh model_vanilla_nodrop.py train_variant.py
for setting in multienv_clean multienv; do
    for seed in 0 1 2; do
        git add runs/VanillaNoDrop_${setting}/seed${seed}/*.pt 2>/dev/null || true
    done
done
git commit -m "VanillaNoDrop control: dropout removal without InEKF (n=3, clean + lm200)

Tests whether the Level15NoDrop win is reducible to 'remove inherited
post-attention dropout' or whether InEKF correction adds independent
value on top of dropout removal.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [vanilla-nodrop-ctrl] Done."
