#!/bin/bash
# DAgger sanity check on MiniGrid-Empty-8x8: minimal navigation env where
# BC should reach high success and DAgger should close any remaining gap.
# If pipeline can't lift performance here, something is structurally wrong.
# If it works here but not on DoorKey, DoorKey is just hard at our scale.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [Empty-DAgger] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [Empty-DAgger] GPUs free."

# Step 1: BC bootstrap on Empty-8x8.
bc_train() {
    local variant=$1 gpu=$2
    mkdir -p "$REPO/runs/${variant}_empty_bc/seed0"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_doorkey_bc \
        --variant $variant --seed 0 \
        --env MiniGrid-Empty-8x8-v0 --tokenization obj_color \
        --max-steps 32 --epochs 20 --n-batches 64 --batch-size 64 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_empty_bc/seed0 \
        > "$LOGS/${variant}_empty_bc_s0.log" 2>&1
}
bc_pair() { bc_train $1 0 & P1=$!; bc_train $2 1 & P2=$!; wait $P1 $P2; }
echo "[$(date)] [Empty-DAgger] BC: Vanilla + Level15"
bc_pair Vanilla Level15
echo "[$(date)] [Empty-DAgger] BC: Level15EM + Level15NoDrop"
bc_pair Level15EM Level15NoDrop

# Step 2: DAgger from BC checkpoints.
dagger_train() {
    local variant=$1 gpu=$2
    mkdir -p "$REPO/runs/${variant}_empty_dagger/seed0"
    local bc_ckpt="mapformer/runs/${variant}_empty_bc/seed0/${variant}_dkbc.pt"
    [ -f "$bc_ckpt" ] || { echo "[skip $variant: no BC ckpt]"; return; }
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_doorkey_dagger \
        --variant $variant --seed 0 \
        --env MiniGrid-Empty-8x8-v0 --tokenization obj_color \
        --max-steps 32 --n-rounds 4 --ep-per-round 384 --inner-epochs 12 \
        --batch-size 32 --lr 1e-4 \
        --init-ckpt $bc_ckpt \
        --output-dir mapformer/runs/${variant}_empty_dagger/seed0 \
        > "$LOGS/${variant}_empty_dagger_s0.log" 2>&1
}
dagger_pair() { dagger_train $1 0 & P1=$!; dagger_train $2 1 & P2=$!; wait $P1 $P2; }
echo "[$(date)] [Empty-DAgger] DAgger: Vanilla + Level15"
dagger_pair Vanilla Level15
echo "[$(date)] [Empty-DAgger] DAgger: Level15EM + Level15NoDrop"
dagger_pair Level15EM Level15NoDrop

echo "[$(date)] [Empty-DAgger] All done."

# Aggregate
python3 -u <<'PYEOF' > "$REPO/DAGGER_EMPTY_RESULTS.md" 2>"$LOGS/dagger_empty_eval.err"
import torch
from pathlib import Path
print("# DAgger sanity check — MiniGrid-Empty-8x8 (pure navigation, no state machine)\n")
print("Tests whether the DAgger pipeline works at all on an easy env.")
print("Empty-8x8 optimal paths are 6-12 actions; BC should achieve high")
print("match-acc, DAgger should close any remaining closed-loop gap.\n")
print("If results here look good (BC > 0.8 closed-loop, DAgger reaches 0.95+),")
print("the DoorKey-8x8 ceiling is task hardness, not pipeline bug.\n")
print("Single seed (seed=0).\n")
print("| Variant | BC match-acc | BC success | After R1 | After R2 | After R3 | After R4 |")
print("|---|---|---|---|---|---|---|")
for v in ["Vanilla", "Level15", "Level15EM", "Level15NoDrop"]:
    bc = Path(f"mapformer/runs/{v}_empty_bc/seed0/{v}_dkbc.pt")
    dg = Path(f"mapformer/runs/{v}_empty_dagger/seed0/{v}_dagger.pt")
    if not bc.exists(): print(f"| {v} | — | — | — | — | — | — |"); continue
    bc_c = torch.load(bc, map_location="cpu", weights_only=False)
    bc_ma = bc_c.get("match_acc", float("nan"))
    bc_su = bc_c.get("success_rate", float("nan"))
    if dg.exists():
        dg_c = torch.load(dg, map_location="cpu", weights_only=False)
        rounds = dg_c.get("round_success", [])
        rs = " | ".join(f"{r:.2f}" for r in rounds[:4])
        rs += " | —" * (4 - len(rounds))
    else:
        rs = "— | — | — | —"
    print(f"| **{v}** | {bc_ma:.2f} | {bc_su:.2f} | {rs} |")
print("\n## Interpretation\n")
print("- Empty-8x8 is a debugging env. If BC success > 0.8 and DAgger reaches")
print("  > 0.95, the pipeline works correctly. The DoorKey-8x8 weak results")
print("  reflect task hardness / model capacity, not implementation bugs.")
print("- If all variants stay low here too, look for pipeline bugs.\n")
print("*Auto-generated by run_dagger_empty.sh, single seed (seed=0)*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add DAGGER_EMPTY_RESULTS.md run_dagger_empty.sh
for v in Vanilla Level15 Level15EM Level15NoDrop; do
    git add runs/${v}_empty_bc/seed0/${v}_dkbc.pt 2>/dev/null || true
    git add runs/${v}_empty_dagger/seed0/${v}_dagger.pt 2>/dev/null || true
done
git commit -m "DAgger sanity check on MiniGrid-Empty-8x8

Tests whether the BC+DAgger pipeline lifts performance on a simple
navigation env (no state machine, 6-12 action optimal paths). If it
works here but not on DoorKey-8x8, the latter is just hard at our
small-model scale. Result in DAGGER_EMPTY_RESULTS.md.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [Empty-DAgger] Done."
