#!/bin/bash
# Capacity control: Level15_ExtraHead on cross-scale.
# Is Level15_Hopfield's +14pp from the Hopfield STRUCTURE or just from
# adding an extra attention head's capacity? ExtraHead adds a GENERIC
# attention head (more params than the Hopfield head) the same residual way.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

train_one() {
    local seed=$1 gpu=$2
    mkdir -p "$REPO/runs/Level15_ExtraHead_multisize/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_multisize \
        --variant Level15_ExtraHead --seed $seed \
        --sizes 32 64 128 --n-envs-per-size 20 --n-landmarks 200 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/Level15_ExtraHead_multisize/seed${seed} \
        > "$LOGS/Level15_ExtraHead_multisize_s${seed}.log" 2>&1
}

echo "[$(date)] seeds 0 + 1 in parallel"
train_one 0 0 & P1=$!
train_one 1 1 & P2=$!
wait $P1 $P2
echo "[$(date)] seed 2"
train_one 2 0
echo "[$(date)] training done"

cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/EXTRAHEAD_CONTROL.md" 2>"$LOGS/extrahead_agg.err"
import torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# Capacity control: is the Hopfield win structure or just an extra head?\n")
print("`Level15_ExtraHead`: Level15 + a GENERIC extra attention head (content")
print("Q/K projections, position-modulated, all-positions causal KV), added the")
print("same residual way as the Hopfield head. 391,980 params — MORE than")
print("Level15_Hopfield (359,213). Conservative capacity control.\n")
print("Cross-scale held-out T=512 OOD, n=3 seeds.\n")
print("| Variant | params | size 32 | size 64 | size 128 |")
print("|---|---|---|---|---|")
pcount = {"Level15": "325,676", "Level15_ExtraHead": "391,980",
          "Level15_Hopfield": "359,213", "TEMFaithful": "~19K"}
for v in ["Level15", "Level15_ExtraHead", "Level15_Hopfield", "TEMFaithful"]:
    per_size = {32: [], 64: [], 128: []}
    for s in [0, 1, 2]:
        p = Path(f"runs/{v}_multisize/seed{s}/{v}_multisize.pt")
        if not p.exists(): continue
        c = torch.load(p, map_location="cpu", weights_only=False)
        er = c.get("eval_results", {})
        for sz in [32, 64, 128]:
            r = er.get(sz, {})
            if r.get("held_T512_acc") is not None:
                per_size[sz].append(r["held_T512_acc"])
    cells = [fmt(per_size[sz]) for sz in [32, 64, 128]]
    print(f"| **{v}** | {pcount.get(v,'—')} | " + " | ".join(cells) + " |")
print()
print("## Decision\n")
print("- **ExtraHead ≈ Level15_Hopfield (~0.92)**: the win was capacity / 'just another head.' The Hopfield structure is not special.")
print("- **ExtraHead ≈ Level15 (~0.78)**: capacity alone does nothing. The Hopfield structure (position-only key, obs-restricted KV) is what closes the gap — despite ExtraHead having MORE parameters.")
print("- **ExtraHead between the two**: capacity contributes partially; structure contributes the rest.\n")
print("*Auto-generated by run_extrahead_control.sh*")
PYEOF

git pull --rebase 2>&1 | tail -3
git add model_inekf_level15_extrahead.py train_variant.py \
    run_extrahead_control.sh EXTRAHEAD_CONTROL.md
for seed in 0 1 2; do
    git add runs/Level15_ExtraHead_multisize/seed${seed}/*.pt 2>/dev/null || true
done
git commit -m "Capacity control: Level15_ExtraHead — is the Hopfield win structure or capacity?

Adds a generic extra attention head (content Q/K, position-modulated,
all-positions KV) the same residual way as the Hopfield head. 391,980
params — MORE than Level15_Hopfield (359,213). If this conservative
capacity control fails to close the cross-scale gap, the Hopfield
structure (position-only key, obs-restricted KV) is what matters.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] done."
