#!/bin/bash
# NumberLineWorld first cut: arithmetic as navigation.
# Vanilla vs Level15 on a 1D additive torus (N=64). Tests whether
# MapFormer's path-integration accumulator does modular arithmetic, and
# whether the InEKF correction helps on OOD-length chains (more ops than
# trained — the self-correcting-accumulator hypothesis).
#
# Seed-outer-loop: seed 0 of both variants lands the first comparison.
# GPU 0 (GPU 1 is another user's). Shares GPU 0 compute with the TEM chain.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"
GPU=0

train_one() {
    local variant=$1 seed=$2
    mkdir -p "$REPO/runs/${variant}_numberline/seed${seed}"
    CUDA_VISIBLE_DEVICES=$GPU python3 -u -m mapformer.train_numberline \
        --variant "$variant" --seed $seed \
        --size 64 --n-obs-types 16 --n-landmarks 0 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_numberline/seed${seed} \
        > "$LOGS/${variant}_numberline_s${seed}.log" 2>&1
}

for seed in 0 1 2; do
    for variant in Vanilla Level15; do
        echo "[$(date)] training $variant numberline seed $seed"
        train_one "$variant" $seed
    done
    # commit progressively so the seed-0 comparison is reviewable early
    cd "$REPO"
    python3 -u <<'PYEOF' > "$REPO/NUMBERLINE_RESULTS.md" 2>"$LOGS/numberline_agg.err"
import torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# NumberLineWorld: arithmetic as navigation (first cut)\n")
print("MapFormer on a 1D additive torus (N=64, 6 ops: ±1/±2/±3). The path")
print("integrator theta = omega * cumsum(f_Delta(action)) literally computes")
print("(a+b+c+...) mod N. Task: predict the obs token at a REVISITED value —")
print("i.e. recall what you saw at a number you've reached before, possibly")
print("via a different path.\n")
print("Train chain = 128 ops; OOD chain = 512 ops (4x longer than trained).\n")
print("| Variant | in-dist T=128 | OOD chain T=512 | T=512 NLL |")
print("|---|---|---|---|")
for v in ["Vanilla", "Level15"]:
    t1, t4, n4 = [], [], []
    for s in [0, 1, 2]:
        p = Path(f"runs/{v}_numberline/seed{s}/{v}_numberline.pt")
        if not p.exists(): continue
        c = torch.load(p, map_location="cpu", weights_only=False)
        if c.get("test_acc") is not None: t1.append(c["test_acc"])
        if c.get("test_acc_T2") is not None: t4.append(c["test_acc_T2"])
        if c.get("test_nll_T2") is not None: n4.append(c["test_nll_T2"])
    print(f"| **{v}** | {fmt(t1)} | {fmt(t4)} | {fmt(n4)} |")
print()
print("## Reading\n")
print("- **Level15 >> Vanilla on OOD chain**: the InEKF self-correcting")
print("  accumulator extrapolates to longer arithmetic chains where the")
print("  uncorrected path integrator drifts. The error-corrected-arithmetic")
print("  story has legs.")
print("- **Level15 ~ Vanilla**: at this N/chain length the uncorrected cumsum")
print("  is already fine; need longer chains or larger N to expose drift.")
print("- **Both low in-dist**: the aliased-obs recall task itself is hard on")
print("  the number line; revisit-prediction needs work.\n")
print("*Auto-generated by run_numberline.sh — progressively updated per seed.*")
PYEOF
    git add NUMBERLINE_RESULTS.md number_line_env.py train_numberline.py run_numberline.sh 2>/dev/null
    for vv in Vanilla Level15; do
        for ss in 0 1 2; do
            git add runs/${vv}_numberline/seed${ss}/*.pt 2>/dev/null || true
        done
    done
    git commit -m "NumberLineWorld: arithmetic-as-navigation first cut (through seed ${seed})" 2>&1 | tail -2
    git push origin main 2>&1 | tail -2
    cd /home/prashr
done
echo "[$(date)] numberline first cut done."
