#!/bin/bash
# TEM parameter-scaling sweep: is TEM's performance saturated at low params?
# Trains TEMFaithful at d_g in {32, 128, 256} on lm200 single-env, n=3.
# (d_g=64 = existing TEMFaithful_lm200.) Then evaluates all four d_g values.
#
# d_g=256 (~291K params) is parameter-matched to Level15 (~305K).
# If TEM saturates (dg256 ~ dg64), TEM's solving power is the fixed Hopfield
# algorithm, not parameter count.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS" "$REPO/paper_figures/tem_scaling"

# GPU 1 is currently used by another user; pin everything to GPU 0 and run
# sequentially. First wait for the capacity-control pipeline to finish so we
# don't contend on GPU 0.
GPU=0
CAP_PID=1855461
echo "[$(date)] waiting for capacity control (PID $CAP_PID) to finish..."
while kill -0 "$CAP_PID" 2>/dev/null; do sleep 60; done
echo "[$(date)] capacity control done; starting TEM scaling on GPU $GPU"

train_one() {
    local variant=$1 seed=$2
    mkdir -p "$REPO/runs/${variant}_lm200/seed${seed}"
    CUDA_VISIBLE_DEVICES=$GPU python3 -u -m mapformer.train_variant \
        --variant "$variant" --seed $seed \
        --n-landmarks 200 --grid-size 64 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_lm200/seed${seed} \
        > "$LOGS/${variant}_lm200_s${seed}.log" 2>&1
}

# Seed-outer-loop, fully sequential on one GPU.
for seed in 0 1 2; do
    for variant in TEMFaithful_dg32 TEMFaithful_dg128 TEMFaithful_dg256; do
        echo "[$(date)] training $variant seed $seed"
        train_one "$variant" $seed
    done
done
echo "[$(date)] training done"

# Eval all four d_g values (dg64 = TEMFaithful)
ED=$REPO/paper_figures/tem_scaling
eval_one() {
    local variant=$1 ckname=$2 seed=$3
    local ckpt="$REPO/runs/${variant}_lm200/seed${seed}/${ckname}.pt"
    [ -f "$ckpt" ] || { echo "  miss $variant s$seed"; return; }
    CUDA_VISIBLE_DEVICES=0 python3 -m mapformer.eval_single_env \
        --variant "$variant" --checkpoint "$ckpt" \
        > "$ED/${variant}_s${seed}.json" 2>"$LOGS/temscale_eval_${variant}_s${seed}.err"
}
echo "[$(date)] evaluating"
for s in 0 1 2; do
    eval_one TEMFaithful_dg32  TEMFaithful_dg32  $s
    eval_one TEMFaithful       TEMFaithful       $s
    eval_one TEMFaithful_dg128 TEMFaithful_dg128 $s
    eval_one TEMFaithful_dg256 TEMFaithful_dg256 $s
done

cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/TEM_SCALING_RESULTS.md" 2>"$LOGS/tem_scaling_agg.err"
import json, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# TEM parameter-scaling sweep: is TEM's performance saturated?\n")
print("TEMFaithful at d_g in {32, 64, 128, 256}. A_a (the per-action transition")
print("matrices, the bulk of TEM's learnable 'model') scales as 4*d_g^2.")
print("d_g=256 (~291K total params) is parameter-matched to Level15 (~305K).\n")
print("Single-env lm200, n=3 seeds, eval_single_env.\n")
print("| Variant | d_g | total params | T=128 acc | T=512 OOD acc | T=512 NLL |")
print("|---|---|---|---|---|---|")
rows = [("TEMFaithful_dg32", 32, "32,766"),
        ("TEMFaithful", 64, "45,086"),
        ("TEMFaithful_dg128", 128, "94,302"),
        ("TEMFaithful_dg256", 256, "291,038")]
for variant, dg, pc in rows:
    a128, a512, n512 = [], [], []
    for s in [0, 1, 2]:
        p = Path(f"paper_figures/tem_scaling/{variant}_s{s}.json")
        if not p.exists(): continue
        j = json.loads(p.read_text())
        if j.get("acc_T128") is not None: a128.append(j["acc_T128"])
        if j.get("acc_T512") is not None: a512.append(j["acc_T512"])
        if j.get("nll_T512") is not None: n512.append(j["nll_T512"])
    print(f"| **{variant}** | {dg} | {pc} | {fmt(a128)} | {fmt(a512)} | {fmt(n512)} |")
print()
print("## Decision\n")
print("- **dg256 ≈ dg64 (saturated)**: TEM's task performance is NOT parameter-limited. The fixed Hopfield retrieval algorithm does the work; A_a only needs enough capacity to represent the action dynamics. Strong evidence for the inductive-bias account — TEM is parameter-efficient because the hard part (associative memory) is algorithmic, not learned.")
print("- **dg256 >> dg64 (scales)**: TEM is merely under-parameterised at the default d_g; it would benefit from scale like any model.")
print("- **dg32 << dg64 (underfit floor)**: locates the minimum d_g needed to represent the 4 action rotations.\n")
print("*Auto-generated by run_tem_scaling.sh*")
PYEOF

git pull --rebase 2>&1 | tail -3
git add model_tem_scaling.py train_variant.py run_tem_scaling.sh \
    TEM_SCALING_RESULTS.md paper_figures/tem_scaling/ 2>/dev/null
for variant in TEMFaithful_dg32 TEMFaithful_dg128 TEMFaithful_dg256; do
    for s in 0 1 2; do
        git add runs/${variant}_lm200/seed${s}/*.pt 2>/dev/null || true
    done
done
git commit -m "TEM parameter-scaling sweep: is TEM saturated at low params?

Trains TEMFaithful at d_g in {32,128,256} on lm200 (d_g=64 already exists).
A_a scales as 4*d_g^2; d_g=256 (~291K) is parameter-matched to Level15.
If TEM saturates, its solving power is the fixed Hopfield retrieval
algorithm — not parameter count — confirming the inductive-bias account
of TEM's parameter efficiency.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -2
echo "[$(date)] done."
