#!/bin/bash
# Cross-topology generalization: torus + open + walls grids.
# Train 4 variants × 1 seed × 50 epochs. ~1-1.5h compute.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [topology] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [topology] GPUs free."

train() {
    local variant=$1 seed=$2 gpu=$3
    mkdir -p "$REPO/runs/${variant}_topology/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_topology \
        --variant $variant --seed $seed \
        --topologies torus open walls \
        --size 64 --n-envs-per-topology 20 --n-landmarks 200 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_topology/seed${seed} \
        > "$LOGS/${variant}_topology_s${seed}.log" 2>&1
}
run_pair() { train $1 0 0 & P1=$!; train $2 0 1 & P2=$!; wait $P1 $P2; }

echo "[$(date)] [topology] RoPE + Vanilla"
run_pair RoPE Vanilla
echo "[$(date)] [topology] Level15GSF_NoDrop + Level15GSF_NoDrop_K16"
run_pair Level15GSF_NoDrop Level15GSF_NoDrop_K16
echo "[$(date)] [topology] All done."

python3 -u <<'PYEOF' > "$REPO/TOPOLOGY_RESULTS.md" 2>"$LOGS/topology_eval.err"
import torch
from pathlib import Path
print("# Cross-topology generalization (torus + open + walls)\n")
print("Trained on mixed topologies: torus (wraparound), open (clamped boundary),")
print("walls (torus + internal walls). 20 envs per topology = 60 train envs total.")
print("Each batch trajectory samples a random topology + random env.")
print("Eval on held-out instances of each topology separately.\n")
print("Each topology requires different position-tracking strategy:")
print("- Torus: cumulative angle wraps naturally")
print("- Open: position clamps at boundary, action may be no-op")
print("- Walls: action may be no-op at walls, breaking smooth path-integration\n")
print("## Held-out accuracy per topology\n")
print("| Variant | torus T=128 | torus T=512 | open T=128 | open T=512 | walls T=128 | walls T=512 |")
print("|---|---|---|---|---|---|---|")
for v in ["RoPE", "Vanilla", "Level15GSF_NoDrop", "Level15GSF_NoDrop_K16"]:
    ckpt = Path(f"mapformer/runs/{v}_topology/seed0/{v}_topology.pt")
    if not ckpt.exists(): print(f"| {v} | — | — | — | — | — | — |"); continue
    c = torch.load(ckpt, map_location="cpu", weights_only=False)
    er = c.get("eval_results", {})
    cells = []
    for topo in ["torus", "open", "walls"]:
        r = er.get(topo, {})
        cells.append(f"{r.get('held_T128_acc', float('nan')):.3f}")
        cells.append(f"{r.get('held_T512_acc', float('nan')):.3f}")
    print(f"| **{v}** | " + " | ".join(cells) + " |")
print()
print("## Interpretation\n")
print("- If MapFormer variants generalize across topologies (high accuracy on all 3): cognitive map machinery is topology-agnostic")
print("- If walls is much worse than torus/open: path-integration breaks at no-op actions (model can't detect them)")
print("- If RoPE crashes everywhere: standard transformer can't handle ANY of these topologies")
print("- K=16 vs K=8 comparison: do more modes help cross-topology (as they did cross-scale)?\n")
print("*Auto-generated by run_topology.sh, single seed (seed=0)*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add TOPOLOGY_RESULTS.md environment_topology.py train_topology.py run_topology.sh
for v in RoPE Vanilla Level15GSF_NoDrop Level15GSF_NoDrop_K16; do
    git add runs/${v}_topology/seed0/${v}_topology.pt 2>/dev/null || true
done
git commit -m "Cross-topology generalization: torus + open + walls grids

Tests cognitive-map generalization across topologies that differ in
position-update dynamics. Each topology requires different path-integration
behavior: torus wraps, open clamps, walls have no-op actions.

4 variants × 1 seed × 50 epochs. Tests whether mode-conditioning helps
cross-topology (where it didn't help cross-scale).
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [topology] Done."
