#!/bin/bash
# Capacity control for the headline Level15-vs-Vanilla comparison.
# Trains Vanilla_ExtraHead (Vanilla + generic extra head, 322K params —
# MORE than Level15's 305K) on lm200, n=3. Then evaluates Vanilla,
# Vanilla_ExtraHead, L15_NoCorr, Level15 identically via eval_single_env.
#
# If Vanilla_ExtraHead stays at Vanilla's level despite >Level15 params,
# the Level15 win is the InEKF correction (architectural), not capacity.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS" "$REPO/paper_figures/capacity_control"

# --- train Vanilla_ExtraHead lm200, n=3 ---
train_one() {
    local seed=$1 gpu=$2
    mkdir -p "$REPO/runs/Vanilla_ExtraHead_lm200/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_variant \
        --variant Vanilla_ExtraHead --seed $seed \
        --n-landmarks 200 --grid-size 64 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/Vanilla_ExtraHead_lm200/seed${seed} \
        > "$LOGS/Vanilla_ExtraHead_lm200_s${seed}.log" 2>&1
}
echo "[$(date)] training Vanilla_ExtraHead lm200 seeds 0+1"
train_one 0 0 & P1=$!
train_one 1 1 & P2=$!
wait $P1 $P2
echo "[$(date)] seed 2"
train_one 2 0
echo "[$(date)] training done"

# --- eval all four variants identically (eval_single_env) ---
ED=$REPO/paper_figures/capacity_control
eval_one() {
    local variant=$1 ckname=$2 dir=$3 seed=$4
    local ckpt="$REPO/runs/${dir}/seed${seed}/${ckname}.pt"
    [ -f "$ckpt" ] || { echo "  miss $variant s$seed"; return; }
    CUDA_VISIBLE_DEVICES=0 python3 -m mapformer.eval_single_env \
        --variant "$variant" --checkpoint "$ckpt" \
        > "$ED/${variant}_s${seed}.json" 2>"$LOGS/cap_eval_${variant}_s${seed}.err"
}
echo "[$(date)] evaluating all variants"
for s in 0 1 2; do
    eval_one Vanilla          Vanilla          Vanilla_lm200          $s
    eval_one Level15          Level15          Level15_lm200          $s
    eval_one Vanilla_ExtraHead Vanilla_ExtraHead Vanilla_ExtraHead_lm200 $s
    eval_one L15_NoCorr       L15_NoCorr       L15_NoCorr_lm200       $s
done

# --- aggregate ---
cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/CAPACITY_CONTROL.md" 2>"$LOGS/capacity_agg.err"
import json, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# Capacity control: is the Level15-over-Vanilla win architecture or parameters?\n")
print("Level15 has ~305K params vs Vanilla's ~256K (+19%). `Vanilla_ExtraHead`")
print("= Vanilla + a generic extra attention head, 322K params — MORE than")
print("Level15. If Vanilla_ExtraHead stays at Vanilla's level, the Level15 win")
print("is the InEKF correction, not capacity.\n")
print("`L15_NoCorr` (305K, Level15 architecture with correction zeroed) is")
print("included as the 'params present but unused' reference.\n")
print("Single-env lm200, n=3 seeds, eval_single_env.\n")
print("| Variant | params | T=128 acc | T=512 OOD acc | T=512 OOD NLL |")
print("|---|---|---|---|---|")
params = {"Vanilla": "255,773", "Vanilla_ExtraHead": "322,077",
          "L15_NoCorr": "305,373", "Level15": "305,373"}
for v in ["Vanilla", "Vanilla_ExtraHead", "L15_NoCorr", "Level15"]:
    a128, a512, n512 = [], [], []
    for s in [0, 1, 2]:
        p = Path(f"paper_figures/capacity_control/{v}_s{s}.json")
        if not p.exists(): continue
        j = json.loads(p.read_text())
        if j.get("acc_T128") is not None: a128.append(j["acc_T128"])
        if j.get("acc_T512") is not None: a512.append(j["acc_T512"])
        if j.get("nll_T512") is not None: n512.append(j["nll_T512"])
    print(f"| **{v}** | {params.get(v,'—')} | {fmt(a128)} | {fmt(a512)} | {fmt(n512)} |")
print()
print("## Decision\n")
print("- **Vanilla_ExtraHead ≈ Vanilla**: +66K usable params do nothing. The Level15 win is the InEKF correction — architectural, not capacity. Headline claim is safe.")
print("- **Vanilla_ExtraHead → Level15**: capacity contributes; the Level15 win is partly parameters. Must report honestly.")
print("- **L15_NoCorr ≈ Vanilla** (expected): confirms the InEKF params, when their correction is disabled, are inert — they only help when actually used as a correction.\n")
print("*Auto-generated by run_capacity_control.sh*")
PYEOF

git pull --rebase 2>&1 | tail -3
git add model_vanilla_extrahead.py train_variant.py run_capacity_control.sh \
    CAPACITY_CONTROL.md paper_figures/capacity_control/ 2>/dev/null
for s in 0 1 2; do
    git add runs/Vanilla_ExtraHead_lm200/seed${s}/*.pt 2>/dev/null || true
done
git commit -m "Capacity control: Vanilla_ExtraHead — is the Level15 win architecture or params?

Level15 (305K) vs Vanilla (256K) is a +19% param gap. Vanilla_ExtraHead
gives Vanilla a generic extra attention head (322K params, MORE than
Level15) with usable capacity. If it stays at Vanilla's level, the
Level15 win is the InEKF correction, not capacity. Eval also includes
L15_NoCorr (Level15 params, correction zeroed) as the unused-params
reference.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -2
echo "[$(date)] done."
