#!/bin/bash
# Two planned post-results experiments:
#   A. Active-inference probe (horizons 1, 4, 8) on single-env lm200 ckpts
#      of Level15 / Vanilla / RoPE / TEMFaithful. Tests "is the trained
#      forward model usable for goal-directed planning?" Single seed of
#      every variant first, per feedback_seed_ordering.
#   B. Single-size Level15 training at grid sizes 16 and 32. Tests the
#      coupled-ω hypothesis from TEM_CROSSSCALE_DIAGNOSTIC.md: if
#      single-size Level15 closes the small-grid gap vs TEM, the
#      multi-scale training was hurting via shared ω.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS" "$REPO/paper_figures/active_inference"

# ============================================================
# A. Active-inference probe sweep
# ============================================================
echo "[$(date)] [A] active-inference probe"
AI_DIR=$REPO/paper_figures/active_inference

probe_ai() {
    local variant=$1 horizon=$2 gpu=$3
    local ckpt="$REPO/runs/${variant}_lm200/seed0/${variant}.pt"
    local out="$AI_DIR/${variant}_h${horizon}_s0.json"
    if [ ! -f "$ckpt" ]; then echo "    skip $variant (no ckpt)"; return; fi
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.probe_active_inference \
        --variant "$variant" --checkpoint "$ckpt" \
        --n-episodes 50 --T-explore 64 --T-navigate 32 \
        --horizon "$horizon" \
        --output-json "$out" \
        > "$LOGS/ai_${variant}_h${horizon}.log" 2>&1
}

for horizon in 1 4 8; do
    echo "  horizon=$horizon"
    probe_ai Vanilla   $horizon 0 & P1=$!
    probe_ai Level15   $horizon 1 & P2=$!
    wait $P1 $P2
    probe_ai RoPE        $horizon 0 & P1=$!
    probe_ai TEMFaithful $horizon 1 & P2=$!
    wait $P1 $P2
done

# Aggregate A
cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/ACTIVE_INFERENCE_RESULTS.md" 2>"$LOGS/ai_agg.err"
import json
from pathlib import Path

print("# Active-inference probe: is the cognitive map usable for goal-directed action?\n")
print("Frozen single-env lm200 checkpoints (random-walk training, NO goal")
print("conditioning, NO policy training). At each navigate step, for each")
print("candidate action, score by max log p(goal_token) over a `horizon`-step")
print("rollout. Pick argmax. Closed-loop execution — model selects action,")
print("env executes, next obs feeds back.\n")
print("Setup: T_explore=64 random walk → T_navigate=32 active-inference. Goal")
print("= random landmark. 50 episodes/variant. Single seed (s0).\n")
print("**Theoretical caveat:** horizon=1 is structurally limited — the model")
print("predicts only the *next* observation, so log p(goal_token) is only")
print("informative when adjacent to the goal. Multi-step horizons (4, 8) use")
print("Dreamer-style argmax-obs rollouts to extrapolate further.\n")
print("## Closed-loop success rate (50 eps, s0)\n")
print("| Variant | horizon=1 | horizon=4 | horizon=8 |")
print("|---|---|---|---|")
for v in ["RoPE", "Vanilla", "Level15", "TEMFaithful"]:
    row = [f"**{v}**"]
    for h in [1, 4, 8]:
        p = Path(f"paper_figures/active_inference/{v}_h{h}_s0.json")
        if not p.exists(): row.append("—"); continue
        j = json.loads(p.read_text())
        sr = j["success_rate"]
        ratio = j.get("mean_ratio_to_optimal")
        cell = f"{sr:.2f}" if ratio is None else f"{sr:.2f} ({ratio:.1f}× opt)"
        row.append(cell)
    print("| " + " | ".join(row) + " |")
print()
print("*Auto-generated by run_planning_and_scale_controls.sh*")
PYEOF
cd /home/prashr

# ============================================================
# B. Single-size Level15 (sizes 16, 32) — coupled-ω hypothesis test
# ============================================================
echo "[$(date)] [B] single-size Level15 training"

train_single_size() {
    local size=$1 seed=$2 gpu=$3
    mkdir -p "$REPO/runs/Level15_size${size}/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_variant \
        --variant Level15 --seed $seed \
        --grid-size $size --n-landmarks 200 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/Level15_size${size}/seed${seed} \
        > "$LOGS/Level15_size${size}_s${seed}.log" 2>&1
}

for seed in 0 1 2; do
    echo "  seed ${seed}: size 16 + size 32"
    train_single_size 16 $seed 0 & P1=$!
    train_single_size 32 $seed 1 & P2=$!
    wait $P1 $P2
done

# Eval each single-size ckpt at training length + T=512 OOD on held-out trajectories
echo "[$(date)] [B] evaluating single-size ckpts"
for size in 16 32; do
    for seed in 0 1 2; do
        CKPT="$REPO/runs/Level15_size${size}/seed${seed}/Level15.pt"
        if [ ! -f "$CKPT" ]; then continue; fi
        CUDA_VISIBLE_DEVICES=0 python3 -m mapformer.eval_single_env \
            --variant Level15 --checkpoint "$CKPT" \
            --train-T 128 --eval-T2 512 \
            > "$REPO/paper_figures/single_env_eval/Level15_size${size}_s${seed}.json" \
            2> "$LOGS/Level15_size${size}_s${seed}_eval.err"
    done
done

# Aggregate B: compare single-size Level15 to multi-size at same size
cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/SINGLE_SIZE_CONTROL.md" 2>"$LOGS/b_agg.err"
import json, torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# Single-size Level15: does the coupled-ω hypothesis hold?\n")
print("`TEM_CROSSSCALE_DIAGNOSTIC.md` proposed: Level15's path-integrator ω")
print("is shared across grid sizes when trained on a mix, so it learns a")
print("compromise that hurts small grids. Falsifiable test: train Level15 on")
print("a SINGLE size at a time. If single-size Level15 closes the gap vs")
print("TEMFaithful, multi-scale training was the culprit.\n")
print("Single-env lm200, n=3 seeds, single grid size, T=512 OOD.\n")
print("| Variant | size 16 T=512 | size 32 T=512 |")
print("|---|---|---|")

# Level15 single-size from JSON
for size in [16, 32]:
    pass
size_accs = {16: [], 32: []}
for size in [16, 32]:
    for s in [0, 1, 2]:
        p = Path(f"paper_figures/single_env_eval/Level15_size{size}_s{s}.json")
        if not p.exists(): continue
        j = json.loads(p.read_text())
        if j.get("acc_T512") is not None: size_accs[size].append(j["acc_T512"])
print(f"| **Level15 single-size** | {fmt(size_accs[16])} | {fmt(size_accs[32])} |")

# Level15 multi-size from training-saved eval_results
multi_accs = {32: [], 64: [], 128: []}
for s in [0, 1, 2]:
    p = Path(f"runs/Level15_multisize/seed{s}/Level15_multisize.pt")
    if not p.exists(): continue
    c = torch.load(p, map_location="cpu", weights_only=False)
    er = c.get("eval_results", {})
    for sz in [32, 64, 128]:
        r = er.get(sz, {})
        if r.get("held_T512_acc") is not None:
            multi_accs[sz].append(r["held_T512_acc"])
print(f"| Level15 multi-size (32+64+128) | — | {fmt(multi_accs[32])} |")

# TEMFaithful multi-size for reference (no single-size TEM yet)
tem_multi = {32: []}
for s in [0, 1, 2]:
    p = Path(f"runs/TEMFaithful_multisize/seed{s}/TEMFaithful_multisize.pt")
    if not p.exists(): continue
    c = torch.load(p, map_location="cpu", weights_only=False)
    er = c.get("eval_results", {})
    r = er.get(32, {})
    if r.get("held_T512_acc") is not None:
        tem_multi[32].append(r["held_T512_acc"])
print(f"| TEMFaithful multi-size (reference) | — | {fmt(tem_multi[32])} |")
print()
print("**Interpretation:**\n")
print("- **Level15 single-size 32 >> Level15 multi-size 32:** coupled-ω was the bottleneck. Per-scale ω would close the gap.")
print("- **Level15 single-size 32 ≈ Level15 multi-size 32:** something else (not coupled-ω) is causing the small-grid weakness.")
print("- **Level15 single-size 16 → indicator at smaller scale where the gap should widen.**\n")
print("*Auto-generated by run_planning_and_scale_controls.sh*")
PYEOF

git pull --rebase 2>&1 | tail -3
git add probe_active_inference.py run_planning_and_scale_controls.sh \
    ACTIVE_INFERENCE_RESULTS.md SINGLE_SIZE_CONTROL.md \
    train_variant.py \
    paper_figures/active_inference/ paper_figures/single_env_eval/ 2>/dev/null
for size in 16 32; do
    for seed in 0 1 2; do
        git add runs/Level15_size${size}/seed${seed}/Level15.pt 2>/dev/null || true
    done
done
git commit -m "Active-inference probe (A) + single-size Level15 control (B)

A: probe_active_inference.py at horizons 1/4/8 on single-env lm200 ckpts
   of Level15 / Vanilla / RoPE / TEMFaithful. Tests planning-readiness
   of the frozen forward model via Friston-style action selection.
B: Level15 trained at grid sizes 16 and 32 single-size (no multi-scale
   mixing). Tests the coupled-ω hypothesis from TEM_CROSSSCALE_DIAGNOSTIC.
   Also adds --grid-size arg to train_variant.py (was hardcoded to 64).
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [planning+scale] done."
