#!/bin/bash
# Per-scale ω fix: Level15 cross-scale with per-scale ω heads.
# Tests the architectural fix to the coupled-ω limitation confirmed in
# SINGLE_SIZE_CONTROL.md.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

train_one() {
    local seed=$1 gpu=$2
    mkdir -p "$REPO/runs/Level15_PerScaleOmega_multisize/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_multisize \
        --variant Level15_PerScaleOmega --seed $seed \
        --sizes 32 64 128 --n-envs-per-size 20 --n-landmarks 200 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/Level15_PerScaleOmega_multisize/seed${seed} \
        > "$LOGS/Level15_PerScaleOmega_s${seed}.log" 2>&1
}

# 3 seeds. Pair seed 0 + 1 on the two GPUs; seed 2 runs alone after.
echo "[$(date)] seeds 0 + 1 in parallel"
train_one 0 0 & P1=$!
train_one 1 1 & P2=$!
wait $P1 $P2
echo "[$(date)] seed 2"
train_one 2 0
echo "[$(date)] training done"

# Aggregate: add per-scale ω row to the cross-scale table
cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/PERSCALE_OMEGA_RESULTS.md" 2>"$LOGS/perscale_agg.err"
import torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# Per-scale ω test: did the architectural fix close the cross-scale gap?\n")
print("`SINGLE_SIZE_CONTROL.md` confirmed Level15's coupled-ω hurts cross-scale at")
print("size 32 by ~13pp. This row adds **per-scale ω** (one ω per training scale,")
print("selected at forward time by env-size index). Prediction: closes the gap")
print("vs TEMFaithful, especially at size 32.\n")
print("Cross-scale held-out T=512 OOD, n=3 seeds.\n")
print("| Variant | size 32 | size 64 | size 128 |")
print("|---|---|---|---|")
for v in ["RoPE", "Vanilla", "Level15", "Level15_PerScaleOmega",
          "Level15GSF_NoDrop_K16", "TEMFaithful"]:
    per_size = {32: [], 64: [], 128: []}
    for s in [0, 1, 2]:
        if v == "Level15_PerScaleOmega":
            p = Path(f"runs/{v}_multisize/seed{s}/{v}_multisize.pt")
        else:
            p = Path(f"runs/{v}_multisize/seed{s}/{v}_multisize.pt")
        if not p.exists(): continue
        c = torch.load(p, map_location="cpu", weights_only=False)
        er = c.get("eval_results", {})
        for sz in [32, 64, 128]:
            r = er.get(sz, {})
            if r.get("held_T512_acc") is not None:
                per_size[sz].append(r["held_T512_acc"])
    cells = [fmt(per_size[sz]) for sz in [32, 64, 128]]
    print(f"| **{v}** | " + " | ".join(cells) + " |")
print()
print("## Falsifiable prediction\n")
print("- Level15_PerScaleOmega size 32 ≈ TEMFaithful size 32 (~0.93+): coupled-ω was the bottleneck; the architectural fix works.")
print("- Level15_PerScaleOmega size 32 ≈ Level15 size 32 (~0.78): coupled-ω was not the problem; the small-grid weakness is something else.")
print()
print("*Auto-generated by run_perscale_omega.sh*")
PYEOF

git pull --rebase 2>&1 | tail -3
git add model_inekf_level15_perscale.py train_variant.py train_multisize.py \
    run_perscale_omega.sh PERSCALE_OMEGA_RESULTS.md
for seed in 0 1 2; do
    git add runs/Level15_PerScaleOmega_multisize/seed${seed}/*.pt 2>/dev/null || true
done
git commit -m "Per-scale ω variant: architectural fix for the cross-scale gap

Confirmed empirically in SINGLE_SIZE_CONTROL.md that Level15's coupled
PathIntegrator.omega is the bottleneck at small grids (single-size Level15
at size 32 = 0.908, multi-size = 0.782). This variant gives the model one
learnable ω per training scale, selected at forward time by env_sizes kwarg.

Threading: train_multisize.py detects env_sizes in model.forward signature
and passes per-batch sizes; backward-compatible with all other variants.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] done."
