#!/bin/bash
# Three post-pipeline analyses to wrap up the current results push:
#   1. Finish TEM single-env CLEAN eval (s1, s2) → update TEM_BACKGROUND_BASELINES.md
#   2. Goal-distance probe on single-env lm200 ckpts (seed-0 of all variants first)
#   3. Cross-scale TEM diagnostic (analytical text — no training)
#
# Foreground, both GPUs free at script start.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS" paper_figures

# ============================================================
# (1) Single-env CLEAN eval for TEMFaithful s{0,1,2}
# ============================================================
echo "[$(date)] [post] (1) TEMFaithful single-env clean eval"
JSON_DIR=$REPO/paper_figures/single_env_eval
mkdir -p "$JSON_DIR"
for seed in 0 1 2; do
    CKPT="$REPO/runs/TEMFaithful_clean/seed${seed}/TEMFaithful.pt"
    if [ ! -f "$CKPT" ]; then
        echo "  skip s${seed}: no ckpt"; continue
    fi
    CUDA_VISIBLE_DEVICES=0 python3 -m mapformer.eval_single_env \
        --variant TEMFaithful --checkpoint "$CKPT" \
        > "$JSON_DIR/TEMFaithful_clean_s${seed}.json" \
        2> "$LOGS/tem_clean_eval_s${seed}.err"
done

# Regenerate TEM_BACKGROUND_BASELINES.md with the single-env row populated
python3 -u <<'PYEOF' > "$REPO/TEM_BACKGROUND_BASELINES.md" 2>"$LOGS/tem_bg_regen.err"
import json, torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# TEMFaithful background baselines (clean, no landmarks)\n")
print("Fills two TEM-shaped gaps in the comparison table.\n")

# --- single-env clean ---
print("## Single-env CLEAN (n_landmarks=0)\n")
print("Single env (seed=0), evaluated on held-out random trajectories.\n")
print("| Variant | T=128 acc | T=128 NLL | T=512 OOD acc | T=512 OOD NLL |")
print("|---|---|---|---|---|")
a128, n128, a512, n512 = [], [], [], []
for s in [0, 1, 2]:
    p = Path(f"paper_figures/single_env_eval/TEMFaithful_clean_s{s}.json")
    if not p.exists(): continue
    j = json.loads(p.read_text())
    if j.get("acc_T128") is not None: a128.append(j["acc_T128"])
    if j.get("nll_T128") is not None: n128.append(j["nll_T128"])
    if j.get("acc_T512") is not None: a512.append(j["acc_T512"])
    if j.get("nll_T512") is not None: n512.append(j["nll_T512"])
print(f"| **TEMFaithful** | {fmt(a128)} | {fmt(n128)} | {fmt(a512)} | {fmt(n512)} |\n")

# --- multi-env clean ---
print("## Multi-env held-out CLEAN (n_landmarks=0)\n")
print("| Variant | Train | Held T=128 | Held T=512 OOD |")
print("|---|---|---|---|")
tr, t128, t512 = [], [], []
for s in [0, 1, 2]:
    ckpt = Path(f"mapformer/runs/TEMFaithful_multienv_clean/seed{s}/TEMFaithful_multienv.pt")
    if not ckpt.exists(): continue
    c = torch.load(ckpt, map_location="cpu", weights_only=False)
    if c.get("train_acc") is not None: tr.append(c["train_acc"])
    if c.get("test_acc") is not None: t128.append(c["test_acc"])
    if c.get("test_acc_T2") is not None: t512.append(c["test_acc_T2"])
print(f"| **TEMFaithful** | {fmt(tr)} | {fmt(t128)} | {fmt(t512)} |\n")

print("*Auto-generated by run_post_pipeline_analysis.sh*")
PYEOF

# ============================================================
# (2) Goal-distance probe — seed-0 across variants first
#     (per feedback_seed_ordering: lands full low-confidence table fastest)
# ============================================================
echo "[$(date)] [post] (2) Goal-distance probe (seed-0 sweep)"
PROBE_DIR=$REPO/paper_figures/goal_distance_probe
mkdir -p "$PROBE_DIR"

probe_one() {
    local variant=$1 ckpt_path=$2 gpu=$3
    local out="$PROBE_DIR/${variant}_lm200_s0.json"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.probe_goal_distance \
        --variant "$variant" --checkpoint "$ckpt_path" \
        --n-train-envs 1 --n-test-envs 0 \
        --train-env-seed-base 0 \
        --n-trajectories-per-env 200 \
        --T 128 --n-landmarks 200 \
        --train-goal-frac 0.75 \
        --epochs 20 --batch-size 512 \
        --output-json "$out" \
        > "$LOGS/probe_${variant}_lm200_s0.log" 2>&1
}

# Run on two GPUs in pairs
probe_one Vanilla   "$REPO/runs/Vanilla_lm200/seed0/Vanilla.pt"           0 & P1=$!
probe_one Level15   "$REPO/runs/Level15_lm200/seed0/Level15.pt"           1 & P2=$!
wait $P1 $P2
probe_one RoPE        "$REPO/runs/RoPE_lm200/seed0/RoPE.pt"               0 & P1=$!
probe_one TEMFaithful "$REPO/runs/TEMFaithful_lm200/seed0/TEMFaithful.pt" 1 & P2=$!
wait $P1 $P2

# Aggregate
python3 -u <<'PYEOF' > "$REPO/PROBE_GOAL_DISTANCE.md" 2>"$LOGS/probe_aggregate.err"
import json
from pathlib import Path
print("# Goal-distance probe: does the cognitive map encode goal-relative distance?\n")
print("Frozen backbone trained on RANDOM WALKS (no goal conditioning). Small")
print("2-layer MLP head takes (hidden_state at obs position, frozen")
print("model.token_emb(goal_token)) → predicts BFS distance to goal cell.\n")
print("Single-env lm200, size 64, n_landmarks 200. 75/25 split of landmarks")
print("into train_goals / held-out_goals. Probe trained on train_goals,")
print("evaluated on both. Single seed (s0); add seeds 1, 2 if signal exists.\n")
print("Lower MAE is better; const-baseline is what you get by predicting the")
print("mean distance. Spearman > 0.5 = useful rank-order.\n")
print("## Single-env lm200 (s0)\n")
print("| Variant | train_goals MAE / Spearman | heldout_goals MAE / Spearman | const-baseline |")
print("|---|---|---|---|")
for v in ["RoPE", "Vanilla", "Level15", "TEMFaithful"]:
    p = Path(f"paper_figures/goal_distance_probe/{v}_lm200_s0.json")
    if not p.exists():
        print(f"| **{v}** | — | — | — |"); continue
    j = json.loads(p.read_text())
    r1 = j["results"].get("train_env_train_goals", {})
    r2 = j["results"].get("train_env_heldout_goals", {})
    b = r1.get("mae_const_baseline", float("nan"))
    print(f"| **{v}** | {r1.get('mae', 0):.2f} / {r1.get('spearman', 0):.2f} "
          f"| {r2.get('mae', 0):.2f} / {r2.get('spearman', 0):.2f} "
          f"| {b:.2f} |")
print()
print("*Auto-generated by run_post_pipeline_analysis.sh*")
PYEOF

# ============================================================
# (3) Cross-scale TEM-vs-Kalman diagnostic (analytical writeup)
# ============================================================
echo "[$(date)] [post] (3) Cross-scale TEM dominance writeup"
cat > "$REPO/TEM_CROSSSCALE_DIAGNOSTIC.md" <<'EOF'
# Why does TEMFaithful dominate cross-scale, especially at small grids?

From `TEM_NOVEL_ENV_RESULTS.md`, cross-scale held-out T=512 OOD (n=3):

| Variant                  | size 32       | size 64       | size 128      |
|---|---|---|---|
| **Level15GSF_NoDrop_K16** | 0.826 ± 0.109 | 0.951 ± 0.031 | 0.973 ± 0.019 |
| **TEMFaithful**           | **0.936 ± 0.021** | **0.973 ± 0.006** | **0.981 ± 0.005** |

TEM beats GSF by **+11pp at size 32**, with much tighter seed variance
(0.021 vs 0.109). The advantage shrinks but persists at sizes 64 and 128.

## Mechanistic hypotheses

1. **TEM's W_a is scale-invariant by construction.** `W_a = exp(skew(A_a))`
   is an orthogonal rotation in d_g space. The rotation magnitude is
   learned per discrete action and is the same regardless of grid size.
   At size 32, one "step" covers 1/32 of the torus; at size 128, 1/128.
   TEM's W_a doesn't have to encode this scale — the agent's path is
   just whatever sequence of rotations W_a produces, and memory binds
   (g, x) at each cell.

2. **Level15's PathIntegrator has scale-coupled ω.** The learnable angular
   velocities ω are initialised to span a frequency range tied to
   `grid_size` (see `model.py::PathIntegrator.__init__`):

   ```
   ω_i = ω_max · (1/Δ_max)^(i/(n_b-1))
   ```

   At mixed scales 32 / 64 / 128, the model learns a SHARED ω that has
   to compromise across all three scales. Size 32 is the worst-served
   because its optimal ω range differs most from the average. This
   would predict the seed-level variance pattern too (high std at 32 =
   model didn't converge to a useful ω compromise on some seeds).

3. **TEM's Hopfield retrieval is scale-agnostic.** Memory is keyed by
   `g`, not by spatial coordinates. Retrieval cost / quality doesn't
   depend on how many distinct cells fit on the grid. Level15 attention,
   in contrast, has to learn to attend across longer sequences at
   smaller grids (more revisits per unit length → more candidate keys).

4. **GSF mode initialisation may not help at the small-scale regime.**
   K=16 modes spread `θ_init` offsets across SO(2). At size 32, the
   useful angular resolution per cell is `2π / 32` per step — coarser
   than mode separation. The modes may collapse or fail to capture the
   small-scale structure.

## Falsifiable predictions

- (1) predicts: if we train Level15 with **per-scale ω heads** (one ω
  per scale, gated by the env-size prefix token), the cross-scale gap
  closes. **Cheapest test.**
- (2) predicts: at size 16 (smaller still), the gap should widen further
  for Level15; TEM should hold up. Quick test: retrain on sizes
  {16, 32, 64} instead of {32, 64, 128}.
- (3) predicts: at size 256 (larger still, more cells → harder
  attention regime), the gap should also widen. Less cheap; needs
  bigger compute.
- (4) predicts: K=4 GSF should match K=16 at size 32 (modes weren't
  helping anyway); K=64 should NOT help at size 32 either. Already
  partly verified in MODEOMEGA_FOLLOWUP_RESULTS.md (K-scale is largely
  a wash on torus).

## Workshop takeaway

If we want to defend "MapFormer + correction matches TEM," we need to
address the cross-scale gap honestly. Three honest framings:

1. **"TEM scales better at small grids; we hypothesise this is the
   coupled-ω constraint and propose per-scale ω as a fix."** Frames
   the gap as a known limitation with a proposed remedy.

2. **"At the workshop-relevant scale (size 64+), TEM and Level1.5 are
   tied within seed std."** Restricts the claim to the regimes where
   it actually holds.

3. **"TEM's structural memory is more scale-invariant; Level1.5
   matches on novel envs but cedes at extreme small scales."** Honest
   summary, accepts the gap as a real architectural difference.

Recommend a mix of (1) + (3): claim parity at workshop-relevant scales,
flag the small-scale gap, propose the architectural fix as future work.

*Auto-generated by run_post_pipeline_analysis.sh*
EOF

# ============================================================
# Commit + push
# ============================================================
cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add eval_single_env.py probe_goal_distance.py run_post_pipeline_analysis.sh \
    TEM_BACKGROUND_BASELINES.md PROBE_GOAL_DISTANCE.md TEM_CROSSSCALE_DIAGNOSTIC.md \
    paper_figures/single_env_eval/ paper_figures/goal_distance_probe/ 2>&1 | tail
git commit -m "Post-pipeline analyses: TEM single-env clean eval, goal-distance probe (s0), cross-scale diagnostic

(1) Eval pass for TEMFaithful single-env clean checkpoints (the row was
    missing because train_variant.py doesn't save train/test_acc).
(2) Goal-distance probe on single-env lm200 ckpts, s0 only per the
    'one seed of everything first' workflow rule. Adds seeds 1, 2 if
    s0 shows signal.
(3) Analytical writeup for why TEM beats Level15GSF_NoDrop_K16 at
    cross-scale, especially size 32. Three falsifiable predictions.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [post] Done."
