#!/bin/bash
# Two cross-scale architectural variants in parallel:
#   - Level15EM_PerScaleOmega (Tier 1): EM backbone + per-scale ω.
#     Does fixing A_P make the AND-gate work?
#   - Level15_Hopfield (Tier 2): WM + position-only-keyed Hopfield retrieval
#     head added on top. Does TEM's explicit memory mechanism close the
#     small-grid + sparse-landmark gaps?
#
# Both trained on cross-scale (sizes 32/64/128), n=3 seeds each.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

train_one() {
    local variant=$1 seed=$2 gpu=$3
    mkdir -p "$REPO/runs/${variant}_multisize/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_multisize \
        --variant "$variant" --seed $seed \
        --sizes 32 64 128 --n-envs-per-size 20 --n-landmarks 200 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_multisize/seed${seed} \
        > "$LOGS/${variant}_multisize_s${seed}.log" 2>&1
}

# Seed-outer-loop. Pair the two variants across GPUs.
for seed in 0 1 2; do
    echo "[$(date)] seed ${seed}: EM_PerScale + Hopfield in parallel"
    train_one Level15EM_PerScaleOmega $seed 0 & P1=$!
    train_one Level15_Hopfield        $seed 1 & P2=$!
    wait $P1 $P2
done

# Aggregate into the cross-scale comparison
cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/EM_HOPFIELD_CROSSSCALE.md" 2>"$LOGS/em_hop_agg.err"
import torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# Two new cross-scale variants: does fixing A_P + adding TEM-style memory close the gap?\n")
print("Cross-scale held-out T=512 OOD, n=3 seeds. Two new rows added:\n")
print("- **Level15EM_PerScaleOmega**: EM backbone with per-scale ω. Tests whether")
print("  the AND-gate works once A_P is repaired.")
print("- **Level15_Hopfield**: WM backbone + position-only-keyed Hopfield retrieval")
print("  head (parallel attention head with KV restricted to obs positions, K from")
print("  position-only rotated k0_pos). Tests whether TEM's explicit memory")
print("  mechanism closes the residual gap.\n")
print("| Variant | size 32 | size 64 | size 128 |")
print("|---|---|---|---|")
for v in ["Vanilla", "Level15", "Level15EM", "Level15_PerScaleOmega",
          "Level15EM_PerScaleOmega", "Level15_Hopfield",
          "Level15GSF_NoDrop_K16", "TEMFaithful"]:
    per_size = {32: [], 64: [], 128: []}
    for s in [0, 1, 2]:
        p = Path(f"runs/{v}_multisize/seed{s}/{v}_multisize.pt")
        if not p.exists(): continue
        c = torch.load(p, map_location="cpu", weights_only=False)
        er = c.get("eval_results", {})
        for sz in [32, 64, 128]:
            r = er.get(sz, {})
            if r.get("held_T512_acc") is not None:
                per_size[sz].append(r["held_T512_acc"])
    cells = [fmt(per_size[sz]) for sz in [32, 64, 128]]
    print(f"| **{v}** | " + " | ".join(cells) + " |")
print()
print("## Decision rules\n")
print("- **Level15EM_PerScaleOmega size 32 > Level15_PerScaleOmega**: AND-gate selectivity helps once A_P is repaired. EM backbone earns its keep.")
print("- **Level15EM_PerScaleOmega size 32 < Level15_PerScaleOmega**: AND-gate's no-fallback property hurts even with repaired A_P. WM additive scoring is strictly better.\n")
print("- **Level15_Hopfield size 32 ≈ TEMFaithful (~0.93)**: explicit position-keyed retrieval closes the gap. Workshop-strong: 'we ported TEM's memory mechanism into MapFormer and got TEM-level cross-scale performance at MapFormer's parallel cost.'")
print("- **Level15_Hopfield size 32 ≈ Level15**: explicit memory bolted on top doesn't help. The remaining gap is from a different mechanism (W_a vs f_Δ representation).")
print("- **Level15_Hopfield size 32 ≈ Level15_PerScaleOmega (~0.88)**: marginal effect; per-scale ω was already most of the closeable gap.\n")
print("*Auto-generated by run_em_perscale_and_hopfield.sh*")
PYEOF

git pull --rebase 2>&1 | tail -3
git add model_inekf_level15_em_perscale.py model_inekf_level15_hopfield.py \
    train_variant.py run_em_perscale_and_hopfield.sh EM_HOPFIELD_CROSSSCALE.md
for v in Level15EM_PerScaleOmega Level15_Hopfield; do
    for seed in 0 1 2; do
        git add runs/${v}_multisize/seed${seed}/*.pt 2>/dev/null || true
    done
done
git commit -m "Two new cross-scale variants: Level15EM_PerScaleOmega + Level15_Hopfield

Tier 1 (EM_PerScale): combines EM backbone with per-scale ω fix. Tests
whether the multiplicative AND-gate works once the position channel is
repaired.

Tier 2 (Hopfield): adds a position-only-keyed Hopfield-style retrieval
head on top of Level15 WM. KV restricted to obs positions, K computed
from rotated k0_pos only (no content channel), V is content. This is
the TEM-style explicit memory mechanism bolted into MapFormer's
parallelizable framework. Tests whether content-keyed retrieval closes
the small-grid + sparse-landmark gaps.

Both n=3 seeds on cross-scale (sizes 32/64/128).
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] done."
