#!/bin/bash
# Ablation: Level15_Hopfield_NoMainAP on cross-scale.
# Tests whether MapFormer's position-modulated main attention is even
# necessary once an explicit Hopfield position-keyed memory head exists.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

train_one() {
    local seed=$1 gpu=$2
    mkdir -p "$REPO/runs/Level15_Hopfield_NoMainAP_multisize/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_multisize \
        --variant Level15_Hopfield_NoMainAP --seed $seed \
        --sizes 32 64 128 --n-envs-per-size 20 --n-landmarks 200 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/Level15_Hopfield_NoMainAP_multisize/seed${seed} \
        > "$LOGS/Level15_Hopfield_NoMainAP_multisize_s${seed}.log" 2>&1
}

echo "[$(date)] seeds 0 + 1 in parallel"
train_one 0 0 & P1=$!
train_one 1 1 & P2=$!
wait $P1 $P2
echo "[$(date)] seed 2"
train_one 2 0
echo "[$(date)] training done"

cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/HOPFIELD_NOMAINAP_RESULTS.md" 2>"$LOGS/hop_nomainap_agg.err"
import torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# Is position-modulated main attention necessary, given a Hopfield head?\n")
print("`Level15_Hopfield_NoMainAP`: same as Level15_Hopfield, but the main")
print("transformer attention gets identity rotation (pure content attention).")
print("Position enters the model ONLY through the explicit Hopfield head.\n")
print("This tests MapFormer's core design choice — entangled (position rotates")
print("content attention) vs factored (position kept in a separate memory head,")
print("TEM-style).\n")
print("Cross-scale held-out T=512 OOD, n=3 seeds.\n")
print("| Variant | size 32 | size 64 | size 128 |")
print("|---|---|---|---|")
for v in ["Vanilla", "Level15", "Level15_Hopfield",
          "Level15_Hopfield_NoMainAP", "TEMFaithful"]:
    per_size = {32: [], 64: [], 128: []}
    for s in [0, 1, 2]:
        p = Path(f"runs/{v}_multisize/seed{s}/{v}_multisize.pt")
        if not p.exists(): continue
        c = torch.load(p, map_location="cpu", weights_only=False)
        er = c.get("eval_results", {})
        for sz in [32, 64, 128]:
            r = er.get(sz, {})
            if r.get("held_T512_acc") is not None:
                per_size[sz].append(r["held_T512_acc"])
    cells = [fmt(per_size[sz]) for sz in [32, 64, 128]]
    print(f"| **{v}** | " + " | ".join(cells) + " |")
print()
print("## Decision\n")
print("- **NoMainAP ≈ Level15_Hopfield**: main attention's position channel is REDUNDANT once an explicit position-keyed memory head exists. Big finding — the factored (TEM-style) design is sufficient; MapFormer's entangled position-modulated attention was an unnecessary complication.")
print("- **NoMainAP worse than Level15_Hopfield**: main A_P still contributes — entangled retrieval does something the obs-only Hopfield head can't.")
print("- **NoMainAP worse than base Level15**: position-modulated main attention is load-bearing; the Hopfield head is a supplement, not a replacement.\n")
print("*Auto-generated by run_hopfield_nomainap.sh*")
PYEOF

git pull --rebase 2>&1 | tail -3
git add model_inekf_level15_hopfield_nomainap.py train_variant.py \
    run_hopfield_nomainap.sh HOPFIELD_NOMAINAP_RESULTS.md
for seed in 0 1 2; do
    git add runs/Level15_Hopfield_NoMainAP_multisize/seed${seed}/*.pt 2>/dev/null || true
done
git commit -m "Hopfield NoMainAP ablation: is position-modulated main attention necessary?

Tests MapFormer's core design choice. Level15_Hopfield_NoMainAP removes
the position rotation from the main transformer attention (identity
rotation -> pure content attention); position reaches the model ONLY via
the explicit Hopfield position-keyed retrieval head.

If NoMainAP matches Level15_Hopfield, MapFormer's signature
position-modulated attention is redundant given explicit position-keyed
memory — the factored (TEM-style) design is sufficient.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] done."
