#!/bin/bash
# DoorKey-8x8 behavioural cloning from BFS solver.
# 4 variants × 1 seed, 30 epochs each. Compares against the torus goal-directed
# result on a real MiniGrid RL benchmark.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [DoorKey] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [DoorKey] GPUs free."

train() {
    local variant=$1 gpu=$2
    mkdir -p "$REPO/runs/${variant}_dkbc/seed0"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_doorkey_bc \
        --variant $variant --seed 0 \
        --env MiniGrid-DoorKey-8x8-v0 --tokenization obj_color \
        --epochs 30 --n-batches 64 --batch-size 64 --max-steps 64 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_dkbc/seed0 \
        > "$LOGS/${variant}_dkbc_s0.log" 2>&1
}

run_pair() { train $1 0 & P1=$!; train $2 1 & P2=$!; wait $P1 $P2; }

echo "[$(date)] [DoorKey] Vanilla + Level15"
run_pair Vanilla Level15
echo "[$(date)] [DoorKey] Level15EM + Level15NoDrop"
run_pair Level15EM Level15NoDrop

echo "[$(date)] [DoorKey] All trainings done."

# Aggregate into markdown
python3 -u <<'PYEOF' > "$REPO/DOORKEY_BC_RESULTS.md" 2>"$LOGS/doorkey_bc_eval.err"
import torch
from pathlib import Path

print("# DoorKey-8x8 behavioural cloning — real MiniGrid goal-directed task\n")
print("Expert trajectories generated via state-space BFS over (x, y, dir, has_key,")
print("door_open). Model trained to predict the next expert action at each step.")
print("Single seed, 30 epochs. Two eval metrics:")
print("- **match-acc:** open-loop action-match against expert trajectory")
print("- **success:** closed-loop rollout success rate (model controls agent)\n")
print("| Variant | match-acc | success |")
print("|---|---|---|")
for v in ["Vanilla", "Level15", "Level15EM", "Level15NoDrop"]:
    ckpt = Path(f"mapformer/runs/{v}_dkbc/seed0/{v}_dkbc.pt")
    if not ckpt.exists(): print(f"| {v} | — | — |"); continue
    c = torch.load(ckpt, map_location="cpu", weights_only=False)
    print(f"| **{v}** | {c.get('match_acc', float('nan')):.3f} | {c.get('success_rate', float('nan')):.3f} |")
print("\n## Interpretation\n")
print("DoorKey requires three chained sub-tasks: navigate to key, pickup, navigate")
print("to door + toggle (with key), navigate to goal. Total ~15-25 actions for")
print("optimal solution on 8x8. Tests whether the cognitive map supports compound")
print("sub-goal sequencing on a real env (vs our torus-only result).")
print("\n*Auto-generated by run_doorkey_bc.sh, single seed (seed=0)*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add DOORKEY_BC_RESULTS.md doorkey_solver.py train_doorkey_bc.py run_doorkey_bc.sh
for v in Vanilla Level15 Level15EM Level15NoDrop; do
    git add runs/${v}_dkbc/seed0/${v}_dkbc.pt 2>/dev/null || true
done
git commit -m "DoorKey-8x8 BC: behavioural cloning on MiniGrid via BFS solver

State-space BFS over (x, y, dir, has_key, door_open) generates expert
DoorKey trajectories. 4 variants × 1 seed × 30 epochs. Eval: open-loop
action-match + closed-loop rollout success. Result in DOORKEY_BC_RESULTS.md.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [DoorKey] Done."
