#!/bin/bash
# Fixup pass:
#   - Re-run TEMFaithful goal-distance probe (bug fix: use model_emb.embedding_dim)
#   - Re-aggregate both result MDs from the correct cwd
set -u
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
cd "$REPO"

# (a) Re-run TEMFaithful probe with the fix
PROBE_DIR=$REPO/paper_figures/goal_distance_probe
echo "[$(date)] re-running TEMFaithful goal-distance probe"
cd /home/prashr  # so module path resolves
CUDA_VISIBLE_DEVICES=0 python3 -u -m mapformer.probe_goal_distance \
    --variant TEMFaithful \
    --checkpoint "$REPO/runs/TEMFaithful_lm200/seed0/TEMFaithful.pt" \
    --n-train-envs 1 --n-test-envs 0 \
    --train-env-seed-base 0 \
    --n-trajectories-per-env 200 \
    --T 128 --n-landmarks 200 \
    --train-goal-frac 0.75 \
    --epochs 20 --batch-size 512 \
    --output-json "$PROBE_DIR/TEMFaithful_lm200_s0.json" \
    > "$LOGS/probe_TEMFaithful_lm200_s0.log" 2>&1
cd "$REPO"

# (b) Re-aggregate single-env clean + probe MDs from REPO cwd
python3 -u <<'PYEOF' > "$REPO/TEM_BACKGROUND_BASELINES.md" 2>"$LOGS/tem_bg_regen2.err"
import json, torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# TEMFaithful background baselines (clean, no landmarks)\n")
print("Fills two TEM-shaped gaps in the comparison table.\n")

print("## Single-env CLEAN (n_landmarks=0)\n")
print("Single env (seed=0), evaluated on held-out random trajectories.\n")
print("| Variant | T=128 acc | T=128 NLL | T=512 OOD acc | T=512 OOD NLL |")
print("|---|---|---|---|---|")
a128, n128, a512, n512 = [], [], [], []
for s in [0, 1, 2]:
    p = Path(f"paper_figures/single_env_eval/TEMFaithful_clean_s{s}.json")
    if not p.exists(): continue
    j = json.loads(p.read_text())
    if j.get("acc_T128") is not None: a128.append(j["acc_T128"])
    if j.get("nll_T128") is not None: n128.append(j["nll_T128"])
    if j.get("acc_T512") is not None: a512.append(j["acc_T512"])
    if j.get("nll_T512") is not None: n512.append(j["nll_T512"])
print(f"| **TEMFaithful** | {fmt(a128)} | {fmt(n128)} | {fmt(a512)} | {fmt(n512)} |\n")

print("## Multi-env held-out CLEAN (n_landmarks=0)\n")
print("| Variant | Train | Held T=128 | Held T=512 OOD |")
print("|---|---|---|---|")
tr, t128, t512 = [], [], []
for s in [0, 1, 2]:
    ckpt = Path(f"runs/TEMFaithful_multienv_clean/seed{s}/TEMFaithful_multienv.pt")
    if not ckpt.exists(): continue
    c = torch.load(ckpt, map_location="cpu", weights_only=False)
    if c.get("train_acc") is not None: tr.append(c["train_acc"])
    if c.get("test_acc") is not None: t128.append(c["test_acc"])
    if c.get("test_acc_T2") is not None: t512.append(c["test_acc_T2"])
print(f"| **TEMFaithful** | {fmt(tr)} | {fmt(t128)} | {fmt(t512)} |\n")

print("*Auto-generated by run_fixup.sh*")
PYEOF

python3 -u <<'PYEOF' > "$REPO/PROBE_GOAL_DISTANCE.md" 2>"$LOGS/probe_aggregate2.err"
import json
from pathlib import Path
print("# Goal-distance probe: does the cognitive map encode goal-relative distance?\n")
print("Frozen backbone trained on RANDOM WALKS (no goal conditioning). Small")
print("2-layer MLP head takes (hidden_state at obs position, frozen")
print("model.token_emb(goal_token)) → predicts BFS distance to goal cell.\n")
print("Single-env lm200, size 64, n_landmarks 200. 75/25 split of landmarks")
print("into train_goals / held-out_goals. Probe trained on train_goals,")
print("evaluated on both. Single seed (s0); add seeds 1, 2 if signal exists.\n")
print("Lower MAE is better; const-baseline is what you get by predicting the")
print("mean distance. Spearman > 0.5 = useful rank-order.\n")
print("## Single-env lm200 (s0)\n")
print("| Variant | train_goals MAE / Spearman | heldout_goals MAE / Spearman | const-baseline |")
print("|---|---|---|---|")
for v in ["RoPE", "Vanilla", "Level15", "TEMFaithful"]:
    p = Path(f"paper_figures/goal_distance_probe/{v}_lm200_s0.json")
    if not p.exists():
        print(f"| **{v}** | — | — | — |"); continue
    j = json.loads(p.read_text())
    r1 = j["results"].get("train_env_train_goals", {})
    r2 = j["results"].get("train_env_heldout_goals", {})
    b = r1.get("mae_const_baseline", float("nan"))
    print(f"| **{v}** | {r1.get('mae', 0):.2f} / {r1.get('spearman', 0):.2f} "
          f"| {r2.get('mae', 0):.2f} / {r2.get('spearman', 0):.2f} "
          f"| {b:.2f} |")
print()
print("*Auto-generated by run_fixup.sh*")
PYEOF

# (c) Commit + push
git add probe_goal_distance.py run_fixup.sh PROBE_GOAL_DISTANCE.md TEM_BACKGROUND_BASELINES.md \
    paper_figures/goal_distance_probe/TEMFaithful_lm200_s0.json 2>/dev/null
git commit -m "Fix probe goal-emb dim + aggregator cwd; regenerate MDs

probe_goal_distance.py: use model_emb.embedding_dim for d_goal (was
hardcoded to cfg['d_model'], which broke TEMFaithful where content_emb
has dim d_model//2).

Aggregators were running from wrong cwd, looking for paper_figures/
under /home/prashr/ instead of /home/prashr/mapformer/. JSON files
were correct; only the aggregation was broken. Re-run from REPO cwd.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [fixup] Done."
