#!/bin/bash
# Level15GSF — Gaussian Sum Filter, K=8 parallel Kalman chains, mixture weighting.
# Tests whether multi-modal Bayesian filtering closes the remaining gap to
# TEMFaithful on lm200 OOD T=512.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [GSF] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [GSF] GPUs free."

train() {
    local cfg=$1 lm=$2 noise=$3 seed=$4 gpu=$5
    mkdir -p "$REPO/runs/Level15GSF_${cfg}/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_variant \
        --variant Level15GSF --seed $seed \
        --n-landmarks $lm --p-action-noise $noise \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/Level15GSF_${cfg}/seed${seed} \
        > "$LOGS/Level15GSF_${cfg}_s${seed}.log" 2>&1
}

run_pair() { train $1 $2 $3 $4 0 & P1=$!; train $5 $6 $7 $8 1 & P2=$!; wait $P1 $P2; }

# Only lm200 — that's where the multimodal Bayes hypothesis matters
echo "[$(date)] [GSF] lm200 s0 + lm200 s1"
run_pair lm200 200 0.0 0  lm200 200 0.0 1
echo "[$(date)] [GSF] lm200 s2"
train lm200 200 0.0 2 0
echo "[$(date)] [GSF] trainings done."

python3 -u <<'PYEOF' > "$REPO/GSF_RESULTS.md" 2>"$LOGS/gsf_eval.err"
import torch, torch.nn.functional as F, numpy as np
from pathlib import Path
from mapformer.environment import GridWorld
from mapformer.model_inekf_level15 import MapFormerWM_Level15InEKF
from mapformer.model_inekf_level15_nodrop import MapFormerWM_Level15NoDrop
from mapformer.model_inekf_gsf import MapFormerWM_Level15GSF
from mapformer.model_tem_faithful import TEMFaithful

VARIANT_CLS = {
    "Level15": MapFormerWM_Level15InEKF,
    "Level15NoDrop": MapFormerWM_Level15NoDrop,
    "Level15GSF": MapFormerWM_Level15GSF,
    "TEMFaithful": TEMFaithful,
}

def build(variant, ckpt):
    c = torch.load(ckpt, map_location="cuda", weights_only=False)
    cfg = c["config"]; cls = VARIANT_CLS[variant]
    kw = dict(vocab_size=cfg["vocab_size"], d_model=cfg["d_model"],
              n_heads=cfg["n_heads"], n_layers=cfg["n_layers"], grid_size=cfg["grid_size"])
    if variant == "Level15GSF": kw["n_modes"] = 8
    m = cls(**kw); m.load_state_dict(c["model_state_dict"])
    return m.cuda().eval()

def eval_revisit(model, env, T, n_trials, seed):
    torch.manual_seed(seed); np.random.seed(seed)
    c = tot = 0; nll = 0.0
    with torch.no_grad():
        for _ in range(n_trials):
            tokens, _, rm = env.generate_trajectory(T)
            tt = tokens.unsqueeze(0).cuda()
            try: logits = model(tt[:, :-1])
            except Exception: return None, None
            lp = F.log_softmax(logits, dim=-1)
            preds = lp.argmax(-1)[0]; tgts = tt[0, 1:]; mask = rm[1:].cuda()
            if mask.sum() == 0: continue
            c += (preds[mask] == tgts[mask]).sum().item(); tot += mask.sum().item()
            idx = torch.arange(lp.shape[1], device="cuda")[mask]
            nll += -lp[0, idx, tgts[mask]].sum().item()
    return (c / tot if tot else None, nll / tot if tot else None)

print("# Level15GSF — does multi-modal Bayesian filtering close the TEMFaithful lm200 gap?\n")
print("K=8 parallel Level 1.5 chains with learnable θ_init_k offsets and")
print("cumulative-log-likelihood mixture weights. Compared head-to-head with")
print("Level15 (single chain), Level15NoDrop (single chain + dropout removed),")
print("and TEMFaithful (post-fix lm200 leader).\n")

env_ood = GridWorld(size=64, n_obs_types=16, p_empty=0.5, n_landmarks=200, seed=1000)
print("## lm200 OOD\n| Variant | T=128 OOD | T=512 OOD | T=512 NLL | n |")
print("|---|---|---|---|---|")
for v in ["Level15", "Level15NoDrop", "Level15GSF", "TEMFaithful"]:
    a128s, a512s, n512s = [], [], []
    for s in [0,1,2]:
        ckpt = Path(f"mapformer/runs/{v}_lm200/seed{s}/{v}.pt")
        if not ckpt.exists(): continue
        m = build(v, ckpt)
        a128, _ = eval_revisit(m, env_ood, 128, 200, seed=2000+s)
        a512, n512 = eval_revisit(m, env_ood, 512, 100, seed=2000+s)
        if a128 is not None: a128s.append(a128); a512s.append(a512); n512s.append(n512)
        del m; torch.cuda.empty_cache()
    if not a128s: print(f"| {v} | — | — | — | 0 |"); continue
    print(f"| **{v}** | {np.mean(a128s):.3f} ± {np.std(a128s):.3f} | "
          f"{np.mean(a512s):.3f} ± {np.std(a512s):.3f} | "
          f"{np.mean(n512s):.3f} | {len(a128s)} |")
print("\n*Auto-generated by run_gsf.sh*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add GSF_RESULTS.md run_gsf.sh model_inekf_gsf.py train_variant.py
git add runs/Level15GSF_lm200/seed*/Level15GSF.pt 2>/dev/null || true
git commit -m "Level15GSF: K=8 parallel Kalman chains + mixture weighting on lm200

Tests whether multi-modal Bayesian filtering closes the TEMFaithful lm200
gap. K=8 chains differ only in initial θ_init_k; mixture weights from
cumulative log-likelihood (parallel cumsum). Result in GSF_RESULTS.md.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [GSF] Done."
