#!/bin/bash
# Long-T evaluation on MiniGrid-DoorKey: does Level15 eventually win
# as path-integration drift accumulates beyond what we tested at T=512?
#
# Reuses existing cached-buffer checkpoints (no new training).
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

echo "[$(date)] Long-T eval on Vanilla / Level15 / RoPE x clean/noise checkpoints..."
python3 -u <<'PYEOF' > "$REPO/MINIGRID_DOORKEY_LONGT.md" 2>"$LOGS/mg_longt_eval.err"
import torch, torch.nn.functional as F, numpy as np
from pathlib import Path
from mapformer.minigrid_env import MiniGridWorld
from mapformer.model import MapFormerWM
from mapformer.model_inekf_level15 import MapFormerWM_Level15InEKF
from mapformer.model_baseline_rope import MapFormerWM_RoPE

VARIANT_CLS = {"Vanilla": MapFormerWM, "Level15": MapFormerWM_Level15InEKF,
               "RoPE": MapFormerWM_RoPE}

def build(variant, ckpt_path):
    c = torch.load(ckpt_path, map_location="cuda", weights_only=False)
    cfg = c.get("config", {})
    cls = VARIANT_CLS[variant]
    m = cls(vocab_size=cfg["vocab_size"], d_model=cfg.get("d_model", 128),
            n_heads=cfg.get("n_heads", 2), n_layers=cfg.get("n_layers", 1),
            grid_size=cfg.get("grid_size", 8))
    m.load_state_dict(c["model_state_dict"])
    return m.cuda().eval()

def eval_revisit(model, env, T, n_trials, seed, p_action_noise=0.0):
    torch.manual_seed(seed); np.random.seed(seed)
    c = tot = 0; nll_sum = 0.0
    with torch.no_grad():
        for _ in range(n_trials):
            tokens, _, rm = env.generate_trajectory(T, p_action_noise=p_action_noise)
            tt = tokens.unsqueeze(0).cuda()
            try:
                logits = model(tt[:, :-1])
            except Exception:
                return None, None
            lp = F.log_softmax(logits, dim=-1)
            preds = lp.argmax(-1)[0]; tgts = tt[0, 1:]; mask = rm[1:].cuda()
            if mask.sum() == 0: continue
            c += (preds[mask] == tgts[mask]).sum().item()
            tot += mask.sum().item()
            idx = torch.arange(lp.shape[1], device="cuda")[mask]
            nll_sum += -lp[0, idx, tgts[mask]].sum().item()
    return (c / tot if tot else None, nll_sum / tot if tot else None)

print("# MiniGrid-DoorKey-8x8: long-T evaluation\n")
print("Tests whether Level15 eventually beats Vanilla as path-integration")
print("drift accumulates at T >> 512. Cached-buffer single-seed checkpoints.\n")

variants = ["Vanilla", "Level15", "RoPE"]
T_LIST = [128, 512, 1024, 2048]
N_TRIALS = {128: 100, 512: 50, 1024: 25, 2048: 12}

def make_env(seed):
    return MiniGridWorld(env_name="MiniGrid-DoorKey-8x8-v0",
                          tokenization="obj_color", seed=seed)

for noise_label, noise_dir, eval_noise in [
    ("Primary (no noise)",   "minigrid_doorkey_clean_cached", 0.0),
    ("Ablation (10% noise)", "minigrid_doorkey_noise_cached", 0.10),
]:
    print(f"## {noise_label}\n")
    print("| Variant | T=128 | T=512 | T=1024 | T=2048 |")
    print("|---|---|---|---|---|")
    for v in variants:
        ckpt = Path(f"mapformer/runs/{noise_dir}/{v}/seed0/{v}.pt")
        if not ckpt.exists():
            print(f"| {v} | (no ckpt) | — | — | — |")
            continue
        m = build(v, ckpt)
        env_ood = make_env(seed=1000)
        row = [f"**{v}**"]
        for T in T_LIST:
            a, n = eval_revisit(m, env_ood, T, N_TRIALS[T], seed=2000,
                                p_action_noise=eval_noise)
            row.append(f"{a:.3f} (NLL {n:.3f})" if a is not None else "(err)")
        print("| " + " | ".join(row) + " |")
        del m; torch.cuda.empty_cache()
    print()

print("\n**Prediction:** if Level15's stabilisation matters here,")
print("the gap to Vanilla should grow with T. If they track each other,")
print("the bottleneck is obs-modeling, not position drift.")
print("\n*Auto-generated by run_minigrid_longt.sh*\n")
PYEOF

echo "[$(date)] Eval done."
tail -25 "$REPO/MINIGRID_DOORKEY_LONGT.md"

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add MINIGRID_DOORKEY_LONGT.md run_minigrid_longt.sh
git commit -m "MiniGrid-DoorKey: long-T evaluation (T=128 to 2048)

Tests whether Level15's clean-OOD advantage emerges at very long
sequences as path-integration drift accumulates beyond T=512. Reuses
existing cached-buffer checkpoints; eval-only.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] Done."
