#!/bin/bash
# Multi-env CLEAN baselines for non-TEM variants: Vanilla, RoPE, Level15,
# Level15GSF_NoDrop, n=3 seeds each.
#
# Purpose: fill the 2x2 cell (multi-env x clean) for the non-TEM variants
# so the comparison "does TEM specifically win on landmarks, or does
# multi-env training generally fix attention?" can be answered.
#
# Runs sequential on single GPU at nice -n 15, no GPU-busy gate. ~30-40 min
# per run, 12 runs = ~6-8h wall-clock.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

GPU=0
echo "[$(date)] [me-clean-bg] starting on GPU $GPU"

VARIANTS=("Vanilla" "RoPE" "Level15" "Level15GSF_NoDrop")
for variant in "${VARIANTS[@]}"; do
    for seed in 0 1 2; do
        OUT="$REPO/runs/${variant}_multienv_clean/seed${seed}"
        CKPT="$OUT/${variant}_multienv.pt"
        mkdir -p "$OUT"
        if [ -f "$CKPT" ]; then
            echo "[$(date)] [me-clean-bg] skip ${variant} s${seed} (exists)"
            continue
        fi
        echo "[$(date)] [me-clean-bg] training ${variant} multi-env clean s${seed}"
        nice -n 15 bash -c "CUDA_VISIBLE_DEVICES=$GPU python3 -u -m mapformer.train_multienv \
            --variant $variant --seed $seed \
            --n-landmarks 0 --n-train-envs 50 --n-test-envs 50 \
            --epochs 50 --n-batches 156 \
            --device cuda \
            --output-dir mapformer/runs/${variant}_multienv_clean/seed${seed}" \
            > "$LOGS/${variant}_multienv_clean_s${seed}.log" 2>&1
    done
done

# Aggregate into the same TEM_BACKGROUND_BASELINES.md so the 2x2 is in one place.
cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/MULTIENV_CLEAN_2x2.md" 2>"$LOGS/me_clean_eval.err"
import torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

def collect(variant, setting):
    """Return (train, t128, t512) lists across seeds 0..2."""
    if setting == "multienv_lm200":
        path_tmpl = f"mapformer/runs/{variant}_multienv/seed{{s}}/{variant}_multienv.pt"
    elif setting == "multienv_clean":
        path_tmpl = f"mapformer/runs/{variant}_multienv_clean/seed{{s}}/{variant}_multienv.pt"
    else:
        return [], [], []
    tr, t128, t512 = [], [], []
    for s in [0, 1, 2]:
        p = Path(path_tmpl.format(s=s))
        if not p.exists(): continue
        c = torch.load(p, map_location="cpu", weights_only=False)
        if c.get("train_acc") is not None: tr.append(c["train_acc"])
        if c.get("test_acc") is not None: t128.append(c["test_acc"])
        if c.get("test_acc_T2") is not None: t512.append(c["test_acc_T2"])
    return tr, t128, t512

print("# Multi-env held-out: 2x2 (clean vs landmarks) for all variants (n=3)\n")
print("Disentangles 'TEM wins on landmarks specifically' from 'multi-env training")
print("generally regularises attention.' If non-TEM clean numbers are high too,")
print("the multi-env-training effect explains most of the closing gap on lm200.\n")

variants = ["RoPE", "Vanilla", "Level15", "Level15GSF_NoDrop", "TEMFaithful"]

for setting, label in [("multienv_clean", "Multi-env CLEAN (no landmarks)"),
                       ("multienv_lm200", "Multi-env LM200 (200 landmarks)")]:
    print(f"## {label}\n")
    print("| Variant | Train | Held T=128 | Held T=512 OOD |")
    print("|---|---|---|---|")
    for v in variants:
        tr, t128, t512 = collect(v, setting)
        print(f"| **{v}** | {fmt(tr)} | {fmt(t128)} | {fmt(t512)} |")
    print()

print("*Auto-generated by run_multienv_clean_baselines.sh*")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add MULTIENV_CLEAN_2x2.md run_multienv_clean_baselines.sh
for variant in RoPE Vanilla Level15 Level15GSF_NoDrop; do
    for seed in 0 1 2; do
        git add runs/${variant}_multienv_clean/seed${seed}/*.pt 2>/dev/null || true
    done
done
git commit -m "Multi-env clean baselines: Vanilla / RoPE / Level15 / GSF_NoDrop (n=3)

Fills the 2x2 cell (multi-env x clean) to disentangle TEM's landmark
advantage from multi-env training's regularising effect on attention.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [me-clean-bg] Done."
