#!/bin/bash
# DAgger fine-tune on DoorKey BC checkpoints.
# 4 variants × 4 rounds × ~500 ep/round. Warm-starts from each variant's BC ckpt.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [DAgger] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [DAgger] GPUs free."

train() {
    local variant=$1 gpu=$2
    mkdir -p "$REPO/runs/${variant}_dagger/seed0"
    local bc_ckpt="mapformer/runs/${variant}_dkbc/seed0/${variant}_dkbc.pt"
    [ -f "$bc_ckpt" ] || { echo "[skip $variant: no BC ckpt at $bc_ckpt]"; return; }
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_doorkey_dagger \
        --variant $variant --seed 0 \
        --env MiniGrid-DoorKey-8x8-v0 --tokenization obj_color \
        --max-steps 64 --n-rounds 4 --ep-per-round 384 --inner-epochs 12 \
        --batch-size 32 --lr 1e-4 \
        --init-ckpt $bc_ckpt \
        --output-dir mapformer/runs/${variant}_dagger/seed0 \
        > "$LOGS/${variant}_dagger_s0.log" 2>&1
}
run_pair() { train $1 0 & P1=$!; train $2 1 & P2=$!; wait $P1 $P2; }

echo "[$(date)] [DAgger] Vanilla + Level15"; run_pair Vanilla Level15
echo "[$(date)] [DAgger] Level15EM + Level15NoDrop"; run_pair Level15EM Level15NoDrop
echo "[$(date)] [DAgger] All done."

# Aggregate
python3 -u <<'PYEOF' > "$REPO/DAGGER_RESULTS.md" 2>"$LOGS/dagger_agg.err"
import torch
from pathlib import Path
print("# DAgger on DoorKey-8x8 — closing the BC distribution-shift gap\n")
print("4 rounds of dataset aggregation per variant. Each round: train on")
print("aggregated dataset, eval closed-loop success, roll out + relabel.\n")
print("Warm-started from BC checkpoints (round 0 of `_dkbc`). Single seed.\n")
print("| Variant | BC (round 0) | After R1 | After R2 | After R3 | After R4 |")
print("|---|---|---|---|---|---|")
for v in ["Vanilla", "Level15", "Level15EM", "Level15NoDrop"]:
    bc = Path(f"mapformer/runs/{v}_dkbc/seed0/{v}_dkbc.pt")
    dg = Path(f"mapformer/runs/{v}_dagger/seed0/{v}_dagger.pt")
    if not dg.exists():
        print(f"| {v} | — | — | — | — | — |"); continue
    bc_c = torch.load(bc, map_location="cpu", weights_only=False) if bc.exists() else None
    bc_succ = bc_c.get("success_rate", float("nan")) if bc_c else float("nan")
    dg_c = torch.load(dg, map_location="cpu", weights_only=False)
    rounds = dg_c.get("round_success", [])
    rs = " | ".join(f"{r:.2f}" for r in rounds[:4]) + (" | —" * (4 - len(rounds)))
    print(f"| **{v}** | {bc_succ:.2f} | {rs} |")
print("\n## Interpretation\n")
print("- BC ceiling was 0.19-0.25 across variants (covariate shift).")
print("- If DAgger lifts all to >0.7: closes the distribution-shift gap;")
print("  separation between variants now reflects true cognitive-map quality.")
print("- If Level15* >> Vanilla after DAgger: the better cognitive map")
print("  improves recovery from off-expert states. This is the closed-")
print("  loop equivalent of our torus OOD-explore-length result.\n")
print("*Auto-generated by run_dagger.sh, single seed (seed=0)*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add DAGGER_RESULTS.md train_doorkey_dagger.py run_dagger.sh
for v in Vanilla Level15 Level15EM Level15NoDrop; do
    git add runs/${v}_dagger/seed0/${v}_dagger.pt 2>/dev/null || true
done
git commit -m "DAgger on DoorKey-8x8: close the BC distribution-shift gap

Warm-starts from BC checkpoints, 4 DAgger rounds, ~250 ep/round.
Round-by-round closed-loop success in DAGGER_RESULTS.md. Tests
whether a richer cognitive map (Level15*) actually translates to
better recovery from off-expert states.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [DAgger] Done."
