#!/bin/bash
# Multi-seed cross-class: rerun seeds 1, 2 for the 4 variants.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [multiclass-multiseed] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [multiclass-multiseed] GPUs free."

train() {
    local variant=$1 seed=$2 gpu=$3
    mkdir -p "$REPO/runs/${variant}_multiclass/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_multiclass \
        --variant $variant --seed $seed \
        --n-torus-envs 30 --n-doorkey-envs 30 \
        --n-torus-test 30 --n-doorkey-test 30 \
        --epochs 50 --n-batches 128 --batch-size 64 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_multiclass/seed${seed} \
        > "$LOGS/${variant}_multiclass_s${seed}.log" 2>&1
}
run_pair() { train $1 0 0 & P1=$!; train $2 1 1 & P2=$!; wait $P1 $P2; }

for seed in 1 2; do
    echo "[$(date)] [multiclass-multiseed] seed $seed: RoPE + Vanilla"
    train RoPE $seed 0 & P1=$!
    train Vanilla $seed 1 & P2=$!
    wait $P1 $P2
    echo "[$(date)] [multiclass-multiseed] seed $seed: Level15 + Level15GSF_NoDrop_K16"
    train Level15 $seed 0 & P1=$!
    train Level15GSF_NoDrop_K16 $seed 1 & P2=$!
    wait $P1 $P2
done

echo "[$(date)] [multiclass-multiseed] All done."

python3 -u <<'PYEOF' > "$REPO/MULTICLASS_MULTISEED_RESULTS.md" 2>"$LOGS/multiclass_multiseed_eval.err"
import torch, numpy as np
from pathlib import Path

print("# Cross-class multi-seed (n=3)\n")
print("Multi-seed update to the cross-class result. Originally single-seed; now n=3.\n")
print("## Held-out accuracy per env class (n=3)\n")
print("| Variant | Torus T=128 | Torus T=512 | DoorKey T=128 | DoorKey T=512 |")
print("|---|---|---|---|---|")
for v in ["RoPE", "Vanilla", "Level15", "Level15GSF_NoDrop_K16"]:
    t128, t512, d128, d512 = [], [], [], []
    for s in [0, 1, 2]:
        ckpt = Path(f"mapformer/runs/{v}_multiclass/seed{s}/{v}_multiclass.pt")
        if not ckpt.exists(): continue
        c = torch.load(ckpt, map_location="cpu", weights_only=False)
        er = c.get("eval_results", {})
        tr = er.get("torus", {})
        dr = er.get("doorkey", {})
        if tr.get("held_T128_acc") is not None: t128.append(tr["held_T128_acc"])
        if tr.get("held_T512_acc") is not None: t512.append(tr["held_T512_acc"])
        if dr.get("held_T128_acc") is not None: d128.append(dr["held_T128_acc"])
        if dr.get("held_T512_acc") is not None: d512.append(dr["held_T512_acc"])
    def fmt(arr):
        if not arr: return "—"
        return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"
    print(f"| **{v}** | {fmt(t128)} | {fmt(t512)} | {fmt(d128)} | {fmt(d512)} |")
print("\n*Auto-generated by run_multiclass_multiseed.sh*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add MULTICLASS_MULTISEED_RESULTS.md run_multiclass_multiseed.sh
for v in RoPE Vanilla Level15 Level15GSF_NoDrop_K16; do
    for seed in 1 2; do
        git add runs/${v}_multiclass/seed${seed}/${v}_multiclass.pt 2>/dev/null || true
    done
done
git commit -m "Multi-seed cross-class: n=3 statistics for torus + DoorKey transfer

Adds seeds 1, 2 to the previously single-seed cross-class result.
Confirms that the cognitive-map architecture handles fundamentally
different env classes (different action vocabs, different obs spaces)
with proper confidence intervals.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [multiclass-multiseed] Done."
