#!/bin/bash
# Sweep: position-decode + goal-distance probes over EXPLICIT spatial state
# (theta_hat for Level15-family, theta_path for Vanilla, g for TEMFaithful).
#
# Seed-0 across variants first per feedback_seed_ordering.md.
set -u
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS" "$REPO/paper_figures/state_probe"

POS=$REPO/paper_figures/state_probe/position
GOAL=$REPO/paper_figures/state_probe/goal_distance
mkdir -p "$POS" "$GOAL"

cd /home/prashr

VARIANTS=("Vanilla" "Level15" "TEMFaithful")

# Position-decode (cheap; quick to see if there's any signal)
echo "[$(date)] position-decode probes"
for v in "${VARIANTS[@]}"; do
    CKPT="$REPO/runs/${v}_lm200/seed0/${v}.pt"
    if [ ! -f "$CKPT" ]; then echo "  skip $v: no ckpt"; continue; fi
    echo "  $v"
    CUDA_VISIBLE_DEVICES=0 python3 -u -m mapformer.probe_position_decode \
        --variant "$v" --checkpoint "$CKPT" \
        --n-trajectories 400 --T 128 --epochs 30 --head-hidden 256 \
        --output-json "$POS/${v}_lm200_s0.json" \
        > "$LOGS/pos_${v}_lm200_s0.log" 2>&1
done

# Goal-distance (the workshop-critical one)
echo "[$(date)] goal-distance probes (over explicit state)"
for v in "${VARIANTS[@]}"; do
    CKPT="$REPO/runs/${v}_lm200/seed0/${v}.pt"
    if [ ! -f "$CKPT" ]; then echo "  skip $v: no ckpt"; continue; fi
    echo "  $v"
    CUDA_VISIBLE_DEVICES=0 python3 -u -m mapformer.probe_goal_distance_state \
        --variant "$v" --checkpoint "$CKPT" \
        --n-trajectories 400 --T 128 --epochs 30 --head-hidden 256 \
        --output-json "$GOAL/${v}_lm200_s0.json" \
        > "$LOGS/goalstate_${v}_lm200_s0.log" 2>&1
done

# Aggregate
cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/STATE_PROBES.md" 2>"$LOGS/state_probe_agg.err"
import json
from pathlib import Path
print("# Spatial-state probes: position decode + goal-distance (s0)\n")
print("Reads the explicit spatial state from each model:\n")
print("- **Level15:** ``model.last_theta_hat`` (InEKF-corrected angles).\n")
print("- **Vanilla:** ``theta_path`` recomputed on the fly (uncorrected cumsum of action deltas).\n")
print("- **TEMFaithful:** ``g`` (structural code) via manual step rollout.\n")
print("\nNot the post-LayerNorm hidden state used by ``probe_goal_distance.py``.\n")
print("\n## Position decode (displacement from start)\n")
print("Target: agent (dx, dy) mod 64. Encoded as cos/sin so the head can")
print("predict on the circle. 'MAE cells' = average torus-distance between\n")
print("predicted and true displacement. Random-guess baseline ~32 cells.\n")
print("| Variant | state dim | MAE (cells) | median (cells) | chance (cells) |")
print("|---|---|---|---|---|")
for v in ["Vanilla", "Level15", "TEMFaithful"]:
    p = Path(f"paper_figures/state_probe/position/{v}_lm200_s0.json")
    if not p.exists():
        print(f"| **{v}** | — | — | — | — |"); continue
    j = json.loads(p.read_text())
    print(f"| **{v}** | {j['state_dim']} | {j['mae_cells']:.2f} | "
          f"{j['median_cells']:.2f} | {j['chance_baseline_mae_cells']:.2f} |")

print("\n## Goal-distance over explicit state\n")
print("Same head as ``probe_goal_distance.py`` but input is the explicit")
print("spatial state, not the post-LN hidden. Goal embedding is ``token_emb``\n")
print("(frozen). Single-env lm200, 75/25 goal split.\n")
print("| Variant | train_goals MAE / Spearman | heldout_goals MAE / Spearman | const-baseline |")
print("|---|---|---|---|")
for v in ["Vanilla", "Level15", "TEMFaithful"]:
    p = Path(f"paper_figures/state_probe/goal_distance/{v}_lm200_s0.json")
    if not p.exists():
        print(f"| **{v}** | — | — | — |"); continue
    j = json.loads(p.read_text())
    r1 = j["results"].get("train_goals", {})
    r2 = j["results"].get("heldout_goals", {})
    b = r1.get("mae_const_baseline", float("nan"))
    print(f"| **{v}** | {r1.get('mae', 0):.2f} / {r1.get('spearman', 0):.2f} "
          f"| {r2.get('mae', 0):.2f} / {r2.get('spearman', 0):.2f} | {b:.2f} |")
print("\n*Auto-generated by run_state_probes.sh*")
PYEOF

git add probe_position_decode.py probe_goal_distance_state.py \
    run_state_probes.sh STATE_PROBES.md \
    paper_figures/state_probe/ 2>/dev/null
git commit -m "State-level probes: position-decode + goal-distance over theta_hat / theta_path / g

Per-variant explicit spatial state (theta_hat for Level15, theta_path for
Vanilla, g for TEMFaithful), instead of the mixed post-LN hidden the
previous probe read. Target encoded as DISPLACEMENT-from-start so the
model's path-integration output is comparable.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] state-probes done."
