#!/bin/bash
# Multi-size cross-scale generalization training. 4 variants × 1 seed × ~50 epochs.
# Sizes: 32, 64, 128. Tests cross-scale cognitive-map skill.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [multisize] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [multisize] GPUs free."

train() {
    local variant=$1 seed=$2 gpu=$3
    mkdir -p "$REPO/runs/${variant}_multisize/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_multisize \
        --variant $variant --seed $seed \
        --sizes 32 64 128 --n-envs-per-size 20 --n-landmarks 200 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_multisize/seed${seed} \
        > "$LOGS/${variant}_multisize_s${seed}.log" 2>&1
}
run_pair() { train $1 0 0 & P1=$!; train $2 0 1 & P2=$!; wait $P1 $P2; }

echo "[$(date)] [multisize] RoPE + Vanilla"
run_pair RoPE Vanilla
echo "[$(date)] [multisize] Level15GSF_NoDrop + Level15GSF_NoDrop_ModeOmega"
run_pair Level15GSF_NoDrop Level15GSF_NoDrop_ModeOmega
echo "[$(date)] [multisize] All done."

python3 -u <<'PYEOF' > "$REPO/MULTISIZE_RESULTS.md" 2>"$LOGS/multisize_eval.err"
import torch
from pathlib import Path
print("# Multi-size cross-scale generalization\n")
print("Training on a mix of 32×32, 64×64, 128×128 torus envs (20 per size = 60 total).")
print("Each batch trajectory samples a random env (random size + random instance).")
print("Eval on held-out instances of each size separately.\n")
print("**Cognitive-map claim:** the model has to learn a scale-aware or")
print("scale-invariant cognitive-map skill — the per-env contents and the")
print("grid sizes both vary across training trajectories. Can it generalize?\n")
print("Single seed. Lm200 (200 landmarks per env). 50 epochs.\n")
print("## Held-out accuracy per size at T=128 and T=512\n")
print("| Variant | size 32 T=128 | size 32 T=512 | size 64 T=128 | size 64 T=512 | size 128 T=128 | size 128 T=512 |")
print("|---|---|---|---|---|---|---|")
for v in ["RoPE", "Vanilla", "Level15GSF_NoDrop", "Level15GSF_NoDrop_ModeOmega"]:
    ckpt = Path(f"mapformer/runs/{v}_multisize/seed0/{v}_multisize.pt")
    if not ckpt.exists(): print(f"| {v} | — | — | — | — | — | — |"); continue
    c = torch.load(ckpt, map_location="cpu", weights_only=False)
    er = c.get("eval_results", {})
    cells = []
    for size in [32, 64, 128]:
        r = er.get(size, {})
        cells.append(f"{r.get('held_T128_acc', float('nan')):.3f}")
        cells.append(f"{r.get('held_T512_acc', float('nan')):.3f}")
    print(f"| **{v}** | " + " | ".join(cells) + " |")
print()

# Mode-omega diagnostic: did the modes specialize across sizes?
print("## Mode-omega specialization diagnostic\n")
from mapformer.model_inekf_gsf_modeomega import MapFormerWM_Level15GSF_NoDrop_ModeOmega
ckpt = Path("mapformer/runs/Level15GSF_NoDrop_ModeOmega_multisize/seed0/Level15GSF_NoDrop_ModeOmega_multisize.pt")
if ckpt.exists():
    c = torch.load(ckpt, map_location="cpu", weights_only=False)
    cfg = c["config"]
    m = MapFormerWM_Level15GSF_NoDrop_ModeOmega(vocab_size=cfg["vocab_size"],
        d_model=cfg["d_model"], n_heads=cfg["n_heads"], n_layers=cfg["n_layers"],
        grid_size=64, n_modes=8)
    m.load_state_dict(c["model_state_dict"])
    omega = m.omega_modes.detach()  # (K, H, NB)
    K, H, NB = omega.shape
    print(f"- omega_modes shape: {omega.shape}")
    print(f"- mean across K: {omega.mean().item():.4f}")
    print(f"- std across K (averaged over h, nb): {omega.std(dim=0).mean().item():.4f}")
    print(f"- range: [{omega.min().item():.4f}, {omega.max().item():.4f}]")
    print(f"- relative spread: {omega.std(dim=0).mean().item() / abs(omega.mean().item()):.3f}")
    print(f"  (Compare to within-class result 0.084-0.095. Higher spread = stronger specialization across sizes.)")
    print(f"\n- per-mode omega summary (head 0, mean across blocks):")
    for k in range(K):
        mean_w = omega[k, 0].mean().item()
        print(f"  mode {k}: mean omega = {mean_w:.3f}")
else:
    print("Ckpt not found.")
print()

print("*Auto-generated by run_multisize.sh, single seed (seed=0)*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add MULTISIZE_RESULTS.md environment_multisize.py train_multisize.py run_multisize.sh
for v in RoPE Vanilla Level15GSF_NoDrop Level15GSF_NoDrop_ModeOmega; do
    git add runs/${v}_multisize/seed0/${v}_multisize.pt 2>/dev/null || true
done
git commit -m "Multi-size cross-scale generalization (32, 64, 128 torus)

Trains models on a mix of 3 grid sizes, tests on held-out instances of each.
Tests cross-scale cognitive-map skill: the model has to learn scale-aware
or scale-invariant strategies since trajectories come from envs of varying
sizes during training.

Includes mode-omega variant to test whether modes specialize across sizes
(where they did NOT within a single size class).
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [multisize] Done."
