#!/bin/bash
# TEMFaithful background baselines — runs slowly on one GPU at low priority,
# does NOT poll for free GPUs (just shares whatever capacity exists).
#
# Fills two TEM-shaped gaps in the comparison table:
#   - Single-env CLEAN (no landmarks): TEM has been only on single-env lm200
#   - Multi-env CLEAN (no landmarks): the 2x2 missing cell to disentangle the
#     "TEM wins on landmarks" vs "multi-env training fixes attention" confound
#
# Single GPU (GPU 1), nice -n 15, sequential. Each TEMFaithful run ~75 min,
# 6 runs total ~7-8h wall-clock. Auto-commits when done.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

GPU=1
echo "[$(date)] [tem-bg] TEMFaithful background baselines starting on GPU $GPU"

# --- single-env CLEAN (3 seeds) ---
for seed in 0 1 2; do
    OUT="$REPO/runs/TEMFaithful_clean/seed${seed}"
    mkdir -p "$OUT"
    if [ -f "$OUT/TEMFaithful.pt" ]; then
        echo "[$(date)] [tem-bg] skip single-env clean s${seed} (already exists)"
        continue
    fi
    echo "[$(date)] [tem-bg] training single-env clean s${seed}"
    nice -n 15 bash -c "CUDA_VISIBLE_DEVICES=$GPU python3 -u -m mapformer.train_variant \
        --variant TEMFaithful --seed $seed \
        --n-landmarks 0 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/TEMFaithful_clean/seed${seed}" \
        > "$LOGS/TEMFaithful_clean_s${seed}.log" 2>&1
done

# --- multi-env CLEAN (3 seeds) ---
for seed in 0 1 2; do
    OUT="$REPO/runs/TEMFaithful_multienv_clean/seed${seed}"
    mkdir -p "$OUT"
    if [ -f "$OUT/TEMFaithful_multienv.pt" ]; then
        echo "[$(date)] [tem-bg] skip multi-env clean s${seed} (already exists)"
        continue
    fi
    echo "[$(date)] [tem-bg] training multi-env clean s${seed}"
    nice -n 15 bash -c "CUDA_VISIBLE_DEVICES=$GPU python3 -u -m mapformer.train_multienv \
        --variant TEMFaithful --seed $seed \
        --n-landmarks 0 --n-train-envs 50 --n-test-envs 50 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/TEMFaithful_multienv_clean/seed${seed}" \
        > "$LOGS/TEMFaithful_multienv_clean_s${seed}.log" 2>&1
done

# --- aggregate ---
python3 -u <<'PYEOF' > "$REPO/TEM_BACKGROUND_BASELINES.md" 2>"$LOGS/tem_bg_eval.err"
import torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# TEMFaithful background baselines (clean, no landmarks)\n")
print("Fills two TEM-shaped gaps in the comparison table.")
print("Runs sequential at nice -n 15 on a single GPU; does not gate on GPU-busy.\n")

# Single-env clean
print("## Single-env CLEAN (n_landmarks=0)\n")
print("| Variant | T=128 train | T=128 OOD acc | T=512 OOD acc |")
print("|---|---|---|---|")
tr, t128, t512 = [], [], []
for s in [0, 1, 2]:
    ckpt = Path(f"mapformer/runs/TEMFaithful_clean/seed{s}/TEMFaithful.pt")
    if not ckpt.exists(): continue
    c = torch.load(ckpt, map_location="cpu", weights_only=False)
    if c.get("train_acc") is not None: tr.append(c["train_acc"])
    if c.get("test_acc") is not None: t128.append(c["test_acc"])
    if c.get("test_acc_T2") is not None: t512.append(c["test_acc_T2"])
print(f"| **TEMFaithful** | {fmt(tr)} | {fmt(t128)} | {fmt(t512)} |\n")

# Multi-env clean
print("## Multi-env held-out CLEAN (n_landmarks=0)\n")
print("| Variant | Train | Held T=128 | Held T=512 OOD |")
print("|---|---|---|---|")
tr, t128, t512 = [], [], []
for s in [0, 1, 2]:
    ckpt = Path(f"mapformer/runs/TEMFaithful_multienv_clean/seed{s}/TEMFaithful_multienv.pt")
    if not ckpt.exists(): continue
    c = torch.load(ckpt, map_location="cpu", weights_only=False)
    if c.get("train_acc") is not None: tr.append(c["train_acc"])
    if c.get("test_acc") is not None: t128.append(c["test_acc"])
    if c.get("test_acc_T2") is not None: t512.append(c["test_acc_T2"])
print(f"| **TEMFaithful** | {fmt(tr)} | {fmt(t128)} | {fmt(t512)} |\n")

print("\n*Auto-generated by run_tem_background_baselines.sh*")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add TEM_BACKGROUND_BASELINES.md run_tem_background_baselines.sh
for setting in clean multienv_clean; do
    for seed in 0 1 2; do
        git add runs/TEMFaithful_${setting}/seed${seed}/*.pt 2>/dev/null || true
    done
done
git commit -m "TEMFaithful background baselines: single-env clean + multi-env clean (n=3)

Fills the 2x2 gap in the TEM comparison table. Runs slow on one GPU at
nice -n 15 to avoid GPU contention with active development.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [tem-bg] Done."
