#!/bin/bash
# Tier 2: Sparse landmarks (lm10, lm50) — multi-modal Bayes home turf.
# Trains 5-model minimal set × 2 configs × 1 seed. ~50 min on 2 GPUs.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [sparse] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [sparse] GPUs free."

train() {
    local variant=$1 lm=$2 seed=$3 gpu=$4
    local tag="lm${lm}"
    mkdir -p "$REPO/runs/${variant}_${tag}/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_variant \
        --variant $variant --seed $seed \
        --n-landmarks $lm --p-action-noise 0.0 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_${tag}/seed${seed} \
        > "$LOGS/${variant}_${tag}_s${seed}.log" 2>&1
}
run_pair() { train $1 $2 $3 0 & P1=$!; train $4 $5 $6 1 & P2=$!; wait $P1 $P2; }

# Minimal model set, single seed each
for lm in 10 50; do
    echo "[$(date)] [sparse lm${lm}] RoPE + Vanilla"
    run_pair RoPE $lm 0  Vanilla $lm 0
    echo "[$(date)] [sparse lm${lm}] Level15 + Level15GSF_NoDrop"
    run_pair Level15 $lm 0  Level15GSF_NoDrop $lm 0
    echo "[$(date)] [sparse lm${lm}] TEMFaithful"
    train TEMFaithful $lm 0 0
done

echo "[$(date)] [sparse] All done."

# Aggregate
python3 -u <<'PYEOF' > "$REPO/SPARSE_LANDMARKS_RESULTS.md" 2>"$LOGS/sparse_eval.err"
import torch, torch.nn.functional as F, numpy as np
from pathlib import Path
from mapformer.environment import GridWorld
from mapformer.eval_long_t import VARIANT_CLS, build

def eval_revisit(model, env, T, n_trials, seed):
    torch.manual_seed(seed); np.random.seed(seed)
    c = tot = 0; nll = 0.0
    with torch.no_grad():
        for _ in range(n_trials):
            tokens, _, rm = env.generate_trajectory(T)
            tt = tokens.unsqueeze(0).cuda()
            try: logits = model(tt[:, :-1])
            except Exception: return None, None
            lp = F.log_softmax(logits, dim=-1)
            preds = lp.argmax(-1)[0]; tgts = tt[0, 1:]; mask = rm[1:].cuda()
            if mask.sum() == 0: continue
            c += (preds[mask] == tgts[mask]).sum().item(); tot += mask.sum().item()
            idx = torch.arange(lp.shape[1], device="cuda")[mask]
            nll += -lp[0, idx, tgts[mask]].sum().item()
    return (c / tot if tot else None, nll / tot if tot else None)

print("# Sparse landmarks — does multi-modal Bayes help when unique cues are rare?\n")
print("Tests TEM's home turf: fewer landmarks → more aliasing → harder disambiguation.")
print("lm200 (5% density) → lm50 (1.2%) → lm10 (0.25%). Minimal model set, single seed.\n")
print("**Cognitive-map prediction:** the gap RoPE → MapFormer should be larger at")
print("lm10 (Kalman/multimodal Bayes most beneficial). Level15GSF_NoDrop may match")
print("TEMFaithful more closely as ambiguity grows.\n")

for lm in [10, 50, 200]:
    tag = "lm200" if lm == 200 else f"lm{lm}"
    env = GridWorld(size=64, n_obs_types=16, p_empty=0.5, n_landmarks=lm, seed=1000)
    print(f"## n_landmarks = {lm}\n| Variant | T=512 OOD acc | T=512 NLL |\n|---|---|---|")
    for v in ["RoPE", "Vanilla", "Level15", "Level15GSF_NoDrop", "TEMFaithful"]:
        ckpt = Path(f"mapformer/runs/{v}_{tag}/seed0/{v}.pt")
        if not ckpt.exists(): print(f"| {v} | — | — |"); continue
        try: m = build(v, ckpt)
        except Exception as e: print(f"| {v} | err: {e!s:.30} | — |"); continue
        acc, nll = eval_revisit(m, env, 512, 50, seed=2000)
        s = lambda x: f"{x:.3f}" if x is not None else "—"
        print(f"| **{v}** | {s(acc)} | {s(nll)} |")
        del m; torch.cuda.empty_cache()
    print()

print("*Auto-generated by run_sparse_landmarks.sh, single seed (seed=0)*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add SPARSE_LANDMARKS_RESULTS.md run_sparse_landmarks.sh
for lm in 10 50; do
    for v in RoPE Vanilla Level15 Level15GSF_NoDrop TEMFaithful; do
        git add runs/${v}_lm${lm}/seed0/${v}.pt 2>/dev/null || true
    done
done
git commit -m "Sparse landmarks: does multi-modal Bayes help when cues are rare?

Tier 2 cognitive-map test. Trains minimal model set on lm10 / lm50
(versus our existing lm200). Tests whether GSF's multimodal posterior
matters more as landmarks get sparser. Single seed for scoping.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [sparse] Done."
