#!/bin/bash
# Tier 3: Multi-environment generalization (TEM-style cognitive map test).
# Trains 5-model minimal set on 50 envs, evals on 50 held-out envs.
# Standard transformers should fail (no spatial inductive bias for per-env maps);
# MapFormer's path-integration should generalize.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [multienv] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [multienv] GPUs free."

train() {
    local variant=$1 seed=$2 gpu=$3
    mkdir -p "$REPO/runs/${variant}_multienv/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_multienv \
        --variant $variant --seed $seed \
        --n-landmarks 200 --n-train-envs 50 --n-test-envs 50 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_multienv/seed${seed} \
        > "$LOGS/${variant}_multienv_s${seed}.log" 2>&1
}
run_pair() { train $1 0 0 & P1=$!; train $2 0 1 & P2=$!; wait $P1 $P2; }

echo "[$(date)] [multienv] RoPE + Vanilla"
run_pair RoPE Vanilla
echo "[$(date)] [multienv] Level15 + Level15GSF_NoDrop"
run_pair Level15 Level15GSF_NoDrop
echo "[$(date)] [multienv] TEMFaithful"
train TEMFaithful 0 0
echo "[$(date)] [multienv] All done."

python3 -u <<'PYEOF' > "$REPO/MULTIENV_RESULTS.md" 2>"$LOGS/multienv_eval.err"
import torch
from pathlib import Path
print("# Multi-environment generalization — the TEM-style cognitive map test\n")
print("50 training envs, 50 held-out test envs (same hyperparams, different obs_maps")
print("and landmark positions). Each batch trajectory sampled from a random training")
print("env. Eval on held-out envs the model has never seen.\n")
print("**Cognitive-map claim:** A model with the right inductive bias should learn a")
print("META-strategy ('explore any env's structure via path integration, then use it")
print("for revisit prediction'). Standard transformers should fail; MapFormer should")
print("transfer.\n")
print("Single seed, lm200, 50 training envs, 50 held-out test envs.\n")
print("| Variant | Train-env acc | Held-out T=128 acc | Held-out T=512 acc | Train-test gap |")
print("|---|---|---|---|---|")
for v in ["RoPE", "Vanilla", "Level15", "Level15GSF_NoDrop", "TEMFaithful"]:
    ckpt = Path(f"mapformer/runs/{v}_multienv/seed0/{v}_multienv.pt")
    if not ckpt.exists(): print(f"| {v} | — | — | — | — |"); continue
    c = torch.load(ckpt, map_location="cpu", weights_only=False)
    tr = c.get("train_acc", float("nan"))
    te = c.get("test_acc", float("nan"))
    te2 = c.get("test_acc_T2", float("nan"))
    gap = tr - te
    print(f"| **{v}** | {tr:.3f} | {te:.3f} | {te2:.3f} | {gap:+.3f} |")
print("\n## Interpretation\n")
print("- Small train-test gap → real generalization (learned a meta-strategy).")
print("- Large gap → memorisation of training envs.")
print("- RoPE / standard transformers: expected large gap, possibly low absolute acc.")
print("- MapFormer / Level15+ : expected small gap, high absolute acc.\n")
print("*Auto-generated by run_multienv.sh, single seed (seed=0)*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add MULTIENV_RESULTS.md environment_multienv.py train_multienv.py run_multienv.sh
for v in RoPE Vanilla Level15 Level15GSF_NoDrop TEMFaithful; do
    git add runs/${v}_multienv/seed0/${v}_multienv.pt 2>/dev/null || true
done
git commit -m "Multi-environment generalization — TEM-style cognitive map test

Trains on 50 envs, evals on 50 held-out envs. Tests whether each model
has learned a META-STRATEGY for cognitive-map building (would generalize
to novel envs) vs MEMORISED per-env content (large train-test gap).

The cleanest cognitive-map necessity test. Single seed, lm200, minimal
model set: RoPE / Vanilla / Level15 / Level15GSF_NoDrop / TEMFaithful.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [multienv] Done."
