#!/bin/bash
# DAgger on MiniGrid-DoorKey-6x6 — medium-difficulty test.
# 3 subtasks (key, door, goal) like DK-8x8 but shorter optimal paths
# (~12 actions vs 17-25). Tests whether DAgger pipeline lifts performance
# when BC has room to improve but task isn't trivial.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [DK6-DAgger] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [DK6-DAgger] GPUs free."

bc_train() {
    local variant=$1 gpu=$2
    mkdir -p "$REPO/runs/${variant}_dk6_bc/seed0"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_doorkey_bc \
        --variant $variant --seed 0 \
        --env MiniGrid-DoorKey-6x6-v0 --tokenization obj_color \
        --max-steps 40 --epochs 30 --n-batches 64 --batch-size 64 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_dk6_bc/seed0 \
        > "$LOGS/${variant}_dk6_bc_s0.log" 2>&1
}
bc_pair() { bc_train $1 0 & P1=$!; bc_train $2 1 & P2=$!; wait $P1 $P2; }
echo "[$(date)] [DK6-DAgger] BC: Vanilla + Level15"
bc_pair Vanilla Level15
echo "[$(date)] [DK6-DAgger] BC: Level15EM + Level15NoDrop"
bc_pair Level15EM Level15NoDrop

dagger_train() {
    local variant=$1 gpu=$2
    mkdir -p "$REPO/runs/${variant}_dk6_dagger/seed0"
    local bc_ckpt="mapformer/runs/${variant}_dk6_bc/seed0/${variant}_dkbc.pt"
    [ -f "$bc_ckpt" ] || { echo "[skip $variant: no BC ckpt]"; return; }
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_doorkey_dagger \
        --variant $variant --seed 0 \
        --env MiniGrid-DoorKey-6x6-v0 --tokenization obj_color \
        --max-steps 40 --n-rounds 4 --ep-per-round 384 --inner-epochs 12 \
        --batch-size 32 --lr 1e-4 \
        --init-ckpt $bc_ckpt \
        --output-dir mapformer/runs/${variant}_dk6_dagger/seed0 \
        > "$LOGS/${variant}_dk6_dagger_s0.log" 2>&1
}
dagger_pair() { dagger_train $1 0 & P1=$!; dagger_train $2 1 & P2=$!; wait $P1 $P2; }
echo "[$(date)] [DK6-DAgger] DAgger: Vanilla + Level15"
dagger_pair Vanilla Level15
echo "[$(date)] [DK6-DAgger] DAgger: Level15EM + Level15NoDrop"
dagger_pair Level15EM Level15NoDrop
echo "[$(date)] [DK6-DAgger] All done."

python3 -u <<'PYEOF' > "$REPO/DAGGER_DK6_RESULTS.md" 2>"$LOGS/dagger_dk6_eval.err"
import torch
from pathlib import Path
print("# DAgger on MiniGrid-DoorKey-6x6 — medium-difficulty test\n")
print("3 subtasks (find key → open door → reach goal) like DK-8x8, but smaller env.")
print("Optimal paths ~10-15 actions vs 17-25 on 8x8 → less error compounding.")
print("If DAgger pipeline can lift performance here when BC leaves headroom,")
print("the DK-8x8 ceiling really is task hardness, not implementation.\n")
print("Single seed (seed=0), 4 rounds × 12 inner epochs × 384 ep/round.\n")
print("| Variant | BC match-acc | BC success | After R1 | After R2 | After R3 | After R4 |")
print("|---|---|---|---|---|---|---|")
for v in ["Vanilla", "Level15", "Level15EM", "Level15NoDrop"]:
    bc = Path(f"mapformer/runs/{v}_dk6_bc/seed0/{v}_dkbc.pt")
    dg = Path(f"mapformer/runs/{v}_dk6_dagger/seed0/{v}_dagger.pt")
    if not bc.exists(): print(f"| {v} | — | — | — | — | — | — |"); continue
    bc_c = torch.load(bc, map_location="cpu", weights_only=False)
    bc_ma = bc_c.get("match_acc", float("nan"))
    bc_su = bc_c.get("success_rate", float("nan"))
    if dg.exists():
        dg_c = torch.load(dg, map_location="cpu", weights_only=False)
        rounds = dg_c.get("round_success", [])
        rs = " | ".join(f"{r:.2f}" for r in rounds[:4])
        rs += " | —" * (4 - len(rounds))
    else:
        rs = "— | — | — | —"
    print(f"| **{v}** | {bc_ma:.2f} | {bc_su:.2f} | {rs} |")
print("\n## Interpretation\n")
print("DK-8x8 BC closed-loop was 0.19-0.25 across variants (capacity-limited).")
print("DK-6x6 BC should be higher (shorter optimal paths). If DAgger lifts")
print("clearly here (BC + 10-30pp), pipeline works; DK-8x8 just needs more")
print("compute or model capacity.\n")
print("*Auto-generated by run_dagger_dk6.sh, single seed (seed=0)*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add DAGGER_DK6_RESULTS.md run_dagger_dk6.sh
for v in Vanilla Level15 Level15EM Level15NoDrop; do
    git add runs/${v}_dk6_bc/seed0/${v}_dkbc.pt 2>/dev/null || true
    git add runs/${v}_dk6_dagger/seed0/${v}_dagger.pt 2>/dev/null || true
done
git commit -m "DAgger on DoorKey-6x6: medium-difficulty pipeline check

DK-6x6 has the same 3-subtask structure as DK-8x8 but shorter optimal
paths (~10-15 actions vs 17-25). Tests DAgger pipeline at a difficulty
level where BC leaves room to improve but task isn't trivial like Empty.
Result in DAGGER_DK6_RESULTS.md.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [DK6-DAgger] Done."
