#!/bin/bash
# Cross-class training: torus + DoorKey. Tests cognitive-map generalization
# across genuinely different env types (different action vocabularies, different obs spaces).
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

is_gpu_free() {
    local mem util
    while IFS=', ' read -r mem util; do
        mem=${mem//[^0-9]/}; util=${util//[^0-9]/}
        [ -z "$mem" ] && mem=0; [ -z "$util" ] && util=0
        if [ "$mem" -ge 5000 ] || [ "$util" -ge 50 ]; then return 1; fi
    done < <(nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv,noheader,nounits)
    return 0
}

echo "[$(date)] [multiclass] Polling for free GPUs..."
while ! is_gpu_free; do sleep 60; done
echo "[$(date)] [multiclass] GPUs free."

train() {
    local variant=$1 gpu=$2
    mkdir -p "$REPO/runs/${variant}_multiclass/seed0"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_multiclass \
        --variant $variant --seed 0 \
        --n-torus-envs 30 --n-doorkey-envs 30 \
        --n-torus-test 30 --n-doorkey-test 30 \
        --epochs 50 --n-batches 128 --batch-size 64 \
        --device cuda \
        --output-dir mapformer/runs/${variant}_multiclass/seed0 \
        > "$LOGS/${variant}_multiclass_s0.log" 2>&1
}
run_pair() { train $1 0 & P1=$!; train $2 1 & P2=$!; wait $P1 $P2; }

echo "[$(date)] [multiclass] RoPE + Vanilla"
run_pair RoPE Vanilla
echo "[$(date)] [multiclass] Level15 + Level15GSF_NoDrop_K16"
run_pair Level15 Level15GSF_NoDrop_K16
echo "[$(date)] [multiclass] All done."

python3 -u <<'PYEOF' > "$REPO/MULTICLASS_RESULTS.md" 2>"$LOGS/multiclass_eval.err"
import torch
from pathlib import Path
print("# Cross-env-class generalization: torus + DoorKey\n")
print("Trains MapFormer variants on a 50/50 mix of torus envs and MiniGrid-DoorKey-8x8 envs.")
print("Tests whether a single cognitive-map architecture can handle:")
print("- Different action vocabularies (torus 4 cardinal vs DoorKey 7 incl. pickup/toggle)")
print("- Different obs spaces (torus full-cell vs DoorKey egocentric)")
print("- Different optimal strategies (path-find vs key/door manipulation)\n")
print("Unified vocab via disjoint ranges + env-class prefix token at trajectory start.")
print("30 train envs per class, 30 held-out test envs per class.\n")
print("## Held-out accuracy per env class\n")
print("| Variant | Torus T=128 | Torus T=512 | DoorKey T=128 | DoorKey T=512 |")
print("|---|---|---|---|---|")
for v in ["RoPE", "Vanilla", "Level15", "Level15GSF_NoDrop_K16"]:
    ckpt = Path(f"mapformer/runs/{v}_multiclass/seed0/{v}_multiclass.pt")
    if not ckpt.exists(): print(f"| {v} | — | — | — | — |"); continue
    c = torch.load(ckpt, map_location="cpu", weights_only=False)
    er = c.get("eval_results", {})
    cells = []
    for env_class in ["torus", "doorkey"]:
        r = er.get(env_class, {})
        a128 = r.get('held_T128_acc')
        a512 = r.get('held_T512_acc')
        cells.append(f"{a128:.3f}" if a128 is not None else "—")
        cells.append(f"{a512:.3f}" if a512 is not None else "—")
    print(f"| **{v}** | " + " | ".join(cells) + " |")
print()
print("## Interpretation\n")
print("- Both classes near chance: model couldn't fit; cross-class is fundamentally too hard for shared arch")
print("- Torus high, DoorKey low: model defaults to torus skill, doesn't pick up DoorKey")
print("- Both classes reasonable: cognitive map architecture handles fundamentally different env types")
print("- Compare per-class numbers to single-class baselines (torus lm200 ~0.99, DoorKey ~0.93 from prior runs)\n")
print("*Auto-generated by run_multiclass.sh*\n")
PYEOF

cd "$REPO"
git pull --rebase 2>&1 | tail -3
git add MULTICLASS_RESULTS.md environment_multiclass.py train_multiclass.py run_multiclass.sh
for v in RoPE Vanilla Level15 Level15GSF_NoDrop_K16; do
    git add runs/${v}_multiclass/seed0/${v}_multiclass.pt 2>/dev/null || true
done
git commit -m "Cross-env-class training: torus + DoorKey mixed

Trains MapFormer variants on a 50/50 mix of torus and MiniGrid-DoorKey envs.
Tests whether the cognitive-map architecture handles fundamentally different
env classes (different action vocabularies, different obs spaces) under a
unified vocab + env-class prefix token.

Result in MULTICLASS_RESULTS.md.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] [multiclass] Done."
