#!/bin/bash
# Level15EM on cross-scale — gap in coverage. Mechanistically interesting:
# EM's multiplicative AND-gate is structurally closer to TEM's content/position
# retrieval. Test whether the EM backbone closes the small-grid gap to TEM.
set -u
cd /home/prashr
REPO=/home/prashr/mapformer
LOGS=$REPO/logs
mkdir -p "$LOGS"

train_one() {
    local seed=$1 gpu=$2
    mkdir -p "$REPO/runs/Level15EM_multisize/seed${seed}"
    CUDA_VISIBLE_DEVICES=$gpu python3 -u -m mapformer.train_multisize \
        --variant Level15EM --seed $seed \
        --sizes 32 64 128 --n-envs-per-size 20 --n-landmarks 200 \
        --epochs 50 --n-batches 156 \
        --device cuda \
        --output-dir mapformer/runs/Level15EM_multisize/seed${seed} \
        > "$LOGS/Level15EM_multisize_s${seed}.log" 2>&1
}

# 3 seeds — pair 0+1 in parallel, then 2 alone
echo "[$(date)] seeds 0 + 1 in parallel"
train_one 0 0 & P1=$!
train_one 1 1 & P2=$!
wait $P1 $P2
echo "[$(date)] seed 2"
train_one 2 0
echo "[$(date)] training done"

# Aggregate: add Level15EM row to the cross-scale comparison
cd "$REPO"
python3 -u <<'PYEOF' > "$REPO/LEVEL15EM_CROSSSCALE.md" 2>"$LOGS/level15em_cs_agg.err"
import torch, numpy as np
from pathlib import Path

def fmt(arr):
    if not arr: return "—"
    return f"{np.mean(arr):.3f} ± {np.std(arr):.3f} (n={len(arr)})"

print("# Level15EM on cross-scale: does the EM backbone close the small-grid gap?\n")
print("Mechanistic question: EM's `A = softmax(A_X ⊙ A_P)` multiplicative")
print("AND-gate is structurally closer to TEM's position-keyed Hopfield retrieval")
print("than WM's additive scoring. Test whether the EM backbone with Level1.5")
print("correction handles small grids better than WM with same correction.\n")
print("Cross-scale held-out T=512 OOD, n=3 seeds.\n")
print("| Variant | size 32 | size 64 | size 128 |")
print("|---|---|---|---|")
for v in ["Vanilla", "Level15", "Level15EM", "Level15_PerScaleOmega",
          "Level15GSF_NoDrop_K16", "TEMFaithful"]:
    per_size = {32: [], 64: [], 128: []}
    for s in [0, 1, 2]:
        p = Path(f"runs/{v}_multisize/seed{s}/{v}_multisize.pt")
        if not p.exists(): continue
        c = torch.load(p, map_location="cpu", weights_only=False)
        er = c.get("eval_results", {})
        for sz in [32, 64, 128]:
            r = er.get(sz, {})
            if r.get("held_T512_acc") is not None:
                per_size[sz].append(r["held_T512_acc"])
    cells = [fmt(per_size[sz]) for sz in [32, 64, 128]]
    print(f"| **{v}** | " + " | ".join(cells) + " |")
print()
print("## Hypotheses to check\n")
print("- **Level15EM size 32 > Level15 size 32:** AND-gate structurally helps at small grids; EM backbone closes some of the TEM gap.")
print("- **Level15EM size 32 < Level15 size 32:** AND-gate's reliance on A_P backfires when coupled-ω degrades the position channel. WM's additive scoring is the better choice at small grids.")
print("- **Level15EM ≈ Level15:** backbone choice is orthogonal to the small-grid limitation; coupled-ω is the bottleneck regardless.\n")
print("*Auto-generated by run_level15em_crossscale.sh*")
PYEOF

git pull --rebase 2>&1 | tail -3
git add LEVEL15EM_CROSSSCALE.md run_level15em_crossscale.sh
for seed in 0 1 2; do
    git add runs/Level15EM_multisize/seed${seed}/*.pt 2>/dev/null || true
done
git commit -m "Level15EM cross-scale: gap-filling experiment

Tests whether the EM backbone (multiplicative AND-gate, structurally
closer to TEM's position-keyed Hopfield retrieval) handles small grids
better than the WM backbone with the same Level1.5 correction.

Adds Level15EM row to the cross-scale comparison alongside Level15,
Level15_PerScaleOmega, Level15GSF_NoDrop_K16, and TEMFaithful.
" 2>&1 | tail -3
git push origin main 2>&1 | tail -3
echo "[$(date)] done."
