"""Per-run readouts and task floors for TW_STATECHANGE_PREREG.md (CPU by default; device-agnostic).

Everything is computed on ONE fixed eval stream: held-out map env seed 10000, np seed 10**6, 200 walks of T = 1024 words
(the trainer's eval stream), generated by StateChangeWorld so every scored slot carries its stratum.

Accuracy (`acc_pass`): revisit object accuracy per stratum (all / T1 / T1s / T1a / T1clean / T2take / T2drop / T3, see
STRATA_KEYS) under these step interventions (path arms; RoPE only 'intact' and 'intact_rs'):
  intact        the model as trained, eval mode (the registered accuracy)
  intact_rs     the 1/(1-p) attention-dropout scale at eval (rescore_hook's correction, applied to this model only)
  sc_cancel     every complete state clause's NET step removed at its final '.' (the clause's partial sums -- its role
                offsets -- are kept; positions after the clause see exactly the phase they would see with no clause)
  sc_cancel_rs  the same, re-scored
  sc_zero       every state-clause position's step set to 0 (net AND role offsets removed; DirOnly's treatment)
  aside_cancel  the same net cancellation for aside sentences (the calibration analogue on stored text-world runs)
  reliance      every direction word's step replaced by the mean direction step: theta advances identically on every
                move and carries no position (GAIN_PHASE's theta reliance, text version)
Gauge note: the only exact symmetry of the scores is (Delta * k, omega / k); every readout below is a function of
omega * Delta, and the clause-level ones (net displacement, drift over clause positions, net cancellation) involve only
complete optional sentences, which contain no token that occurs exactly once per move, so a per-move shift between
core words (verb <-> direction word) leaves them unchanged.

Geometry (`geometry`), in phase units P = omega * Delta, mean over the 64 channels of |wrap(.)| (rad):
  dstep      the direction half-step: mean over the 12 direction words w of |wrap((P[w] - mean P[opposite synonyms]) / 2)|
             (the common component of opposite directions cancels: per-move-gauge invariant)
  R_take / R_drop / R_aside   mean over the grammar's clause variants (3 verbs or frames x 16 nouns) of the clause's
             NET phase displacement, / dstep: how far, relative to a move, one clause moves the phase (any direction)
  shift_take / shift_drop / shift_aside   the same nets projected on the MAP PLANE (span of the two axis half-steps),
             L2 norm in units of one move (mean L2 norm of the two axis half-steps): how far one clause moves the agent's
             position estimate. shift_sc = (shift_take + shift_drop) / 2 is the REGISTERED geometry readout (B);
             dist_* the off-plane remainder in the same unit
  carry_cos  cosine between the mean take-clause net and the mean drop-clause net (-1: an inventory channel, take +u,
             drop -u); class table: mean |wrap(P[w])| / dstep per word class
Drift (`drift`), on 40 walks of the same stream: for every revisit slot, the phase integrated over positions of one
class only, between the cell's first observed visit and the slot; mean over channels of |wrap(dtheta)|, averaged over
pairs that straddle >= 1 clause of the class (state / aside), or over all pairs (adverb + filler). Also the TW_NORMSTEP
channel count (all positions, a channel drifts if mean |dtheta| > 1 rad).
Floors (`floors`): rules applied to every revisit target, read per stratum; the bookkeeping check replays the cell
contents from the TOKENS (parsed state clauses), the slot locations and the map, and must reproduce every target.
"""
import json
import sys
from collections import Counter, defaultdict

import numpy as np
import torch
import torch.nn.functional as F

from mapformer.environment_textworld import DIRS, VERBS, ADVERBS, FILLERS, SEE, OBJECTS, ASIDE
from mapformer.environment_tw_statechange import StateChangeWorld, TAKE, DROP, DET, CLS
from mapformer.model_textstep import step_of
from mapformer.train_tw_statechange import build, make_env, EVAL_SEED, HELDOUT, PATH_ARMS

wrap = lambda x: (x + np.pi) % (2 * np.pi) - np.pi
STRATA_KEYS = ("all", "T1", "T1s", "T1a", "T1clean", "T2take", "T2drop", "T3")
VARIANTS = ("intact", "intact_rs", "sc_cancel", "sc_cancel_rs", "sc_zero", "aside_cancel", "reliance")
OPP = {0: 1, 1: 0, 2: 3, 3: 2}


# ----------------------------------------------------------------------------------------------------- loading
def load(ck):
    """-> (model in eval mode, arm, env cfg). Reads this batch's checkpoints and the stored text-world ones
    (runs/textworld: variant Vanilla_r4 / RoPE; runs/tw_normstep: arm MapWM / NormStep / NormStepNB / DirOnly)."""
    b = torch.load(ck, map_location="cpu", weights_only=False); a = b["config"]["args"]
    arm = b.get("arm") or {"Vanilla_r4": "MapWM", "RoPE": "RoPE"}[b["variant"]]
    cfg = {"p_take": a.get("p_take", 0.0), "p_drop": a.get("p_drop", 0.0),
           "state_vocab": not a.get("no_state_vocab", "p_take" not in a), "size": a.get("size", 64),
           "n_layers": a.get("n_layers", 1), "seed": b["seed"]}
    env = make_env(cfg["seed"], cfg["size"], cfg["p_take"], cfg["p_drop"], cfg["state_vocab"])
    if arm == "NormStepNB":
        from mapformer.model_textstep import MapWM_NormStepNB
        m = MapWM_NormStepNB(vocab_size=env.unified_vocab_size, d_model=128, n_heads=2, n_layers=cfg["n_layers"],
                             grid_size=cfg["size"])
    else:
        m = build(arm, env, cfg["n_layers"], cfg["size"])
    m.load_state_dict(b["model_state_dict"])
    return m.eval(), arm, cfg


def eval_env(cfg):
    return make_env(HELDOUT, cfg["size"], cfg["p_take"], cfg["p_drop"], cfg["state_vocab"])


def walks(env, n=200, T=1024, seed=EVAL_SEED):
    np.random.seed(seed); W = []
    for _ in range(n):
        tok, _o, rev = env.generate_trajectory(T)
        W.append({"tok": tok, "rev": rev, "pc": env.pos_class.copy(), "info": list(env.slot_info),
                  "clauses": list(env.clauses), "events": list(env.events), "locs": list(env.visited_locations)})
    return W


# ----------------------------------------------------------------------------------------------------- forward
class rescaled:
    """Context: multiply every attention layer's o_proj input by 1/(1-p) (rescore_hook's correction, this model only)."""
    def __init__(self, m, on=True):
        self.m, self.on, self.h = m, on, []

    def __enter__(self):
        if self.on:
            for L in self.m.layers:
                s = 1.0 / (1.0 - L.dropout.p)
                self.h.append(L.o_proj.register_forward_pre_hook(lambda mod, args, s=s: (args[0] * s,) + tuple(args[1:])))
        return self

    def __exit__(self, *e):
        for h in self.h:
            h.remove()


def fwd_steps(m, tokens, steps):
    """MapFormerWM.forward with the per-position step tensor (B, L, H, nb) given (checked equal to m(tokens) when
    steps = step_of(m, tokens): tw_statechange_checks.py)."""
    B, L = tokens.shape
    x = m.token_emb(tokens)
    cos_a, sin_a = m.path_integrator(steps)
    mask = torch.triu(torch.ones(L, L, device=tokens.device, dtype=torch.bool), diagonal=1)
    for layer in m.layers:
        x = layer(x, cos_a, sin_a, mask)
    return m.out_proj(m.out_norm(x))


def _slot_strata(s):
    st = s["stratum"]; ks = ["all", st]
    if st == "T1":
        if s["straddle_sc"]:
            ks.append("T1s")
        if s["straddle_aside"]:
            ks.append("T1a")
        if not s["aside_here"]:
            ks.append("T1clean")
    return ks


@torch.no_grad()
def acc_pass(m, arm, env, W, batch=10, device="cpu"):
    """-> {variant: {stratum: [correct, total]}} on the walks W (argmax accuracy at revisit slots)."""
    path = arm in PATH_ARMS or arm == "NormStepNB"
    var = VARIANTS if path else ("intact", "intact_rs")
    res = {v: {k: [0, 0] for k in STRATA_KEYS} for v in var}
    dir_ids = torch.tensor([i for a in range(4) for i in env.dir_ids[a]], device=device)
    m = m.to(device)
    if path:
        dmean = step_of(m, dir_ids[None])[0].mean(0)                      # (H, nb) mean direction step
    for b0 in range(0, len(W), batch):
        Wb = W[b0:b0 + batch]
        tok = torch.stack([w["tok"] for w in Wb]).to(device); inp = tok[:, :-1]; L = inp.shape[1]
        logits = {}
        if path:
            st = step_of(m, inp)
            for v in var:
                s2 = st
                if v in ("sc_cancel", "sc_cancel_rs", "sc_zero", "aside_cancel"):
                    s2 = st.clone()
                    kinds = ("aside",) if v == "aside_cancel" else ("take", "drop")
                    for j, w in enumerate(Wb):
                        for kind, a_, e_, _c in w["clauses"]:
                            if kind not in kinds or e_ > L:
                                continue
                            if v == "sc_zero":
                                s2[j, a_:e_] = 0
                            else:
                                s2[j, e_ - 1] = s2[j, e_ - 1] - st[j, a_:e_].sum(0)
                elif v == "reliance":
                    s2 = torch.where(torch.isin(inp, dir_ids)[..., None, None], dmean.expand_as(st), st)
                with rescaled(m, v.endswith("_rs")):
                    logits[v] = (m(inp) if v in ("intact", "intact_rs") else fwd_steps(m, inp, s2)).argmax(-1).cpu()
        else:
            for v in var:
                with rescaled(m, v.endswith("_rs")):
                    logits[v] = m(inp).argmax(-1).cpu()
        for j, w in enumerate(Wb):
            for s in w["info"]:
                if not s["rev"]:
                    continue
                p = s["pos"]; y = int(w["tok"][p])
                assert y == s["answer"]
                for v in var:
                    ok = int(logits[v][j, p - 1]) == y
                    for k in _slot_strata(s):
                        res[v][k][0] += ok; res[v][k][1] += 1
    return res


def acc_of(res, v, k):
    c, n = res[v][k]
    return c / n if n else float("nan")


# ----------------------------------------------------------------------------------------------------- geometry
@torch.no_grad()
def step_table(m, env):
    """-> (D (V, 64) raw step per token, omega (64,)), float64."""
    V = env.unified_vocab_size
    D = step_of(m, torch.arange(V)[None])[0].reshape(V, -1).numpy().astype(np.float64)
    return D, m.path_integrator.omega.detach().reshape(-1).numpy().astype(np.float64)


@torch.no_grad()
def geometry(m, env, table=None):
    """table: optional (D, omega) overriding the model's (used by the gauge checks)."""
    D, om = table if table is not None else step_table(m, env)
    P = D * om[None]
    mabs = lambda x: float(np.abs(wrap(x)).mean())
    I = env.idx
    h = [(P[w] - P[env.dir_ids[OPP[a]]].mean(0)) / 2 for a in range(4) for w in env.dir_ids[a]]
    dstep = float(np.mean([mabs(x) for x in h]))
    nouns = [I[w] for w in OBJECTS[:env.n_obs_types]]
    out = {"dstep": dstep, "dir_raw": float(np.mean([mabs(P[w]) for a in range(4) for w in env.dir_ids[a]]))}
    nets = {}
    if "took" in I:
        for kind, verbs in (("take", TAKE), ("drop", DROP)):
            nets[kind] = np.array([P[I["she"]] + P[I[v]] + P[I[DET]] + P[n] + P[I["."]] for v in verbs for n in nouns])
    nets["aside"] = np.array([P[[I[w] for w in fr]].sum(0) + P[n] + P[I["."]] for fr in ASIDE for n in nouns])
    # the map plane: the two axis half-steps (north-south, east-west; synonyms averaged). A clause's FIELD SHIFT is the
    # norm of its net displacement projected on that plane, in units of one move (the mean norm of the two axis
    # half-steps); the rest is distortion (same unit). A projection, not least-squares coefficients: it stays bounded
    # when the two axes are nearly collinear (a least-squares readout gave 10 cells for a 0.08 net on one stored run).
    ax = np.stack([(P[env.dir_ids[0]].mean(0) - P[env.dir_ids[1]].mean(0)) / 2,
                   (P[env.dir_ids[3]].mean(0) - P[env.dir_ids[2]].mean(0)) / 2], 1)          # (64, 2)
    hbar = float(np.linalg.norm(ax, axis=0).mean())
    Q, _ = np.linalg.qr(ax)
    out["axis_cos"] = float(abs(ax[:, 0] @ ax[:, 1]) / np.prod(np.linalg.norm(ax, axis=0)))
    for kind, X in nets.items():
        out[f"R_{kind}"] = float(np.mean([mabs(x) for x in X]) / dstep) if dstep > 0 else float("nan")
        proj = X @ Q @ Q.T
        out[f"shift_{kind}"] = float(np.linalg.norm(proj, axis=1).mean() / hbar) if hbar > 0 else float("nan")
        out[f"dist_{kind}"] = float(np.linalg.norm(X - proj, axis=1).mean() / hbar) if hbar > 0 else float("nan")
    out["R_sc"] = (out["R_take"] + out["R_drop"]) / 2 if "take" in nets else None
    out["shift_sc"] = (out["shift_take"] + out["shift_drop"]) / 2 if "take" in nets else None
    if "take" in nets:
        t, d = nets["take"].mean(0), nets["drop"].mean(0)
        nt, nd = np.linalg.norm(t), np.linalg.norm(d)
        out["carry_cos"] = float(t @ d / (nt * nd)) if nt > 0 and nd > 0 else float("nan")
        out["carry_cancel"] = float(np.linalg.norm(t + d) / ((nt + nd) / 2)) if nt + nd > 0 else float("nan")
    classes = {"verb": VERBS, "adverb": ADVERBS, "filler": FILLERS, "see": [w for p in SEE for w in p],
               "object": OBJECTS[:env.n_obs_types], "nothing": ["nothing"], "period": ["."],
               "aside": [w for p in ASIDE for w in p]}
    if "took" in I:
        classes.update({"take_verb": TAKE, "drop_verb": DROP, "the": [DET]})
    out["class_step"] = {c: float(np.mean([mabs(P[I[w]]) for w in set(ws)]) / dstep) if dstep > 0 else float("nan")
                         for c, ws in classes.items()}
    return out


# ----------------------------------------------------------------------------------------------------- drift
@torch.no_grad()
def drift(m, W, thr=1.0):
    om = m.path_integrator.omega.detach().reshape(-1).numpy()
    sets = {"sc": (CLS["take"], CLS["drop"]), "aside": (CLS["aside"],), "optword": (CLS["adverb"], CLS["filler"])}
    acc = {k: [] for k in sets}; full = []
    for w in W:
        st = step_of(m, w["tok"][None])[0].reshape(len(w["tok"]), -1).numpy()
        th = {k: np.cumsum(st * np.isin(w["pc"], v)[:, None], 0) * om[None] for k, v in sets.items()}
        thf = np.cumsum(st, 0) * om[None]
        first = {}
        for s in w["info"]:
            c = s["cell"]
            if c not in first:
                first[c] = s["pos"]; continue
            i, f = s["pos"], first[c]
            full.append(wrap(thf[i] - thf[f]))
            for k in sets:
                if k == "optword" or (k == "sc" and s["straddle_sc"]) or (k == "aside" and s["straddle_aside"]):
                    acc[k].append(float(np.abs(wrap(th[k][i] - th[k][f])).mean()))
    md = np.abs(np.array(full)).mean(0)
    return {"drift_sc": float(np.mean(acc["sc"])) if acc["sc"] else float("nan"), "n_sc_pairs": len(acc["sc"]),
            "drift_aside": float(np.mean(acc["aside"])) if acc["aside"] else float("nan"),
            "drift_optword": float(np.mean(acc["optword"])), "clock_channels": int((md > thr).sum())}


# ----------------------------------------------------------------------------------------------------- floors
def _dirs_per_slot(w, env):
    word2dir = {i: a for a in range(4) for i in env.dir_ids[a]}
    t = w["tok"].tolist()
    return [word2dir[t[i]] for i in range(len(t)) if w["pc"][i] == CLS["dir"]]


def replay_check(w, env):
    """Rebuild each revisit target from the TOKENS (parsed state clauses), the slot locations and the map alone; True iff
    every target is reproduced. A state clause is attributed to the most recent slot before it."""
    t = w["tok"].tolist()
    take, drop = (set(env.take_ids), set(env.drop_ids)) if hasattr(env, "take_ids") else (set(), set())
    obs_map = env.grid.obs_map.numpy(); K = env.n_obs_types
    word_of = lambda k: env.idx["nothing"] if k >= K else env.idx[OBJECTS[k]]
    slots = [s["pos"] for s in w["info"]]; content = {}
    ev_after = {}
    for i, x in enumerate(t):
        if (x in take or x in drop) and i + 2 < len(t):
            k = max(j for j, p in enumerate(slots) if p < i)
            noun = t[i + 2]
            ev_after[k] = ("take" if x in take else "drop", noun)
    for k, s in enumerate(w["info"]):
        c = tuple(w["locs"][k])
        cur = content.get(c, word_of(int(obs_map[c[0], c[1]])))
        if t[s["pos"]] != cur:                     # every slot, first visits and revisits
            return False
        if k in ev_after:
            kind, noun = ev_after[k]
            content[c] = env.idx["nothing"] if kind == "take" else noun
    return True


def floors(env, W, ngram_env=None, n_train=1500, T=1024, ngram_seed=1):
    """-> {rule: {stratum: acc}} for the state-free and location-free rules, plus counts; n-grams (orders 1-5, over the
    preceding WORDS at revisit slots) are fit on `n_train` walks of `ngram_env` (a training map) if given."""
    nothing = env.idx["nothing"]
    rules = defaultdict(lambda: defaultdict(list)); ys = []
    for w in W:
        t = w["tok"].tolist(); dirs = _dirs_per_slot(w, env); last_drop = None
        for k, s in enumerate(w["info"]):
            if s["rev"]:
                y = t[s["pos"]]; ys.append(y)
                rev_ = k >= 2 and dirs[k] == OPP[dirs[k - 1]]
                rc = t[w["info"][k - 2]["pos"]] if rev_ else nothing
                if rev_:
                    e = w["events"][k - 2]
                    rcs = (nothing if e[0] == "take" else env.idx[OBJECTS[e[1]]]) if e is not None else rc
                else:
                    rcs = nothing
                pred = {"first_saw": s["first_saw"], "last_saw": s["last_saw"], "revcopy": rc, "revcopy_state": rcs,
                        "last_dropped": last_drop if last_drop is not None else nothing, "y": y}
                for rname, p in pred.items():
                    for kk in _slot_strata(s):
                        rules[rname][kk].append(p == y if rname != "y" else y)
            e = w["events"][k]
            if e is not None and e[0] == "drop":
                last_drop = env.idx[OBJECTS[e[1]]]
    const_word = Counter(ys).most_common(1)[0][0]
    out = {r: {k: float(np.mean(v)) for k, v in d.items()} for r, d in rules.items() if r != "y"}
    out["constant"] = {k: float(np.mean([y == const_word for y in v])) for k, v in rules["y"].items()}
    out["counts"] = {k: len(v) for k, v in rules["y"].items()}
    out["constant_word"] = env.vocab[const_word]
    if ngram_env is not None:
        np.random.seed(ngram_seed); TR = []
        for _ in range(n_train):
            tok, _o, rev = ngram_env.generate_trajectory(T); TR.append((tok.tolist(), np.nonzero(rev.numpy())[0]))
        for n in range(1, 6):
            tab = defaultdict(Counter)
            for tl, idx in TR:
                for i in idx:
                    tab[tuple(tl[i - n:i])][tl[i]] += 1
            hits = defaultdict(list)
            for w in W:
                t = w["tok"].tolist()
                for s in w["info"]:
                    if not s["rev"]:
                        continue
                    i = s["pos"]; c = tab.get(tuple(t[i - n:i]))
                    p = c.most_common(1)[0][0] if c else const_word
                    for kk in _slot_strata(s):
                        hits[kk].append(p == t[i])
            out[f"ngram{n}"] = {k: float(np.mean(v)) for k, v in hits.items()}
    return out


NONPATH_RULES = ("constant", "ngram1", "ngram2", "ngram3", "ngram4", "ngram5", "revcopy", "revcopy_state", "last_dropped")


def nonpath_floor(fl, stratum):
    """Best location-free (or short-range-only) rule on a stratum: C's floor F."""
    vals = {r: fl[r][stratum] for r in NONPATH_RULES if r in fl and stratum in fl[r]}
    r = max(vals, key=vals.get)
    return vals[r], r


# ----------------------------------------------------------------------------------------------------- per run
def readouts(ck, W=None, Wd=None, device="cpu"):
    m, arm, cfg = load(ck); env = eval_env(cfg)
    W = W if W is not None else walks(env)
    res = acc_pass(m, arm, env, W, device=device); m = m.cpu()
    r = {"arm": arm, "acc": {v: {k: acc_of(res, v, k) for k in STRATA_KEYS} for v in res},
         "n": {k: res["intact"][k][1] for k in STRATA_KEYS}}
    if arm in PATH_ARMS or arm == "NormStepNB":
        r["geom"] = geometry(m, env)
        r.update(drift(m, Wd if Wd is not None else W[:40]))
        a = r["acc"]
        r["L_sc"] = a["sc_cancel"]["T1s"] - a["intact"]["T1s"]
        r["L_sc_rs"] = a["sc_cancel_rs"]["T1s"] - a["intact_rs"]["T1s"]
        r["L_sc_all"] = a["sc_cancel"]["all"] - a["intact"]["all"]
        r["L_sc0"] = a["sc_zero"]["all"] - a["intact"]["all"]
        r["L_aside"] = a["aside_cancel"]["T1a"] - a["intact"]["T1a"]
        r["reliance"] = a["intact"]["all"] - a["reliance"]["all"]
    return r


if __name__ == "__main__":
    print(json.dumps(readouts(sys.argv[1]), indent=1, default=float))
