"""Gates for the code-modelling arm. Run BEFORE any training.

Standing rules this implements:
  - Gate BEFORE training, not after.
  - Report the task's measured FLOOR beside every headline. Dyck's F1 had an
    0.88 no-stack floor and two batches were read below it; the same mistake is
    available here and is the main thing these gates exist to prevent.
  - A gate must CALL the task code (rule 7): the annotations are re-derived
    from the written byte stream, not trusted from the builder.

G1  leakage        no file, and no file CONTENT, in two splits
G2  annotations    every recorded offset really is that bracket, in the written
                   bytes, and every opener really matches its closer
G3  stratum mass   how many scored positions each depth/distance cell holds,
                   so an underpowered cell is known before it is read
G4  floors         majority-class and no-stack n-gram accuracy per stratum,
                   orders 1..8, trained on train and scored on val
G5  chance         the uniform-over-closers rate, stated explicitly
"""

import argparse
import hashlib
import json
import os
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

# Relative paths in `python3 -m mapformer.X` resolve to the PARENT dir, not the
# package dir, and fail silently -- this is the fifth occurrence in the project.
# Anchor every default path to the module's own location.
_REPO = os.path.dirname(os.path.abspath(__file__))

CLOSER_BYTES = [ord(")"), ord("]"), ord("}")]
OPENER_BYTES = [ord("("), ord("["), ord("{")]
DEPTH_BINS = [(1, 1), (2, 2), (3, 4), (5, 8), (9, 10 ** 9)]
DIST_BINS = [(0, 2), (3, 8), (9, 32), (33, 128), (129, 10 ** 9)]


def bin_of(v, bins):
    for i, (lo, hi) in enumerate(bins):
        if lo <= v <= hi:
            return i
    return len(bins) - 1


def label(bins, i):
    lo, hi = bins[i]
    return f"{lo}+" if hi > 10 ** 8 else f"{lo}-{hi}"


def load(dd, name):
    data = np.fromfile(dd / f"code_{name}.bin", dtype=np.uint8)
    z = np.load(dd / f"code_{name}_brackets.npz")
    return data, z["pos"], z["kind"], z["open_pos"], z["depth"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default=os.path.join(_REPO, "data"))
    ap.add_argument("--max-order", type=int, default=8)
    ap.add_argument("--out", default=os.path.join(_REPO, "CODE_GATES.md"))
    args = ap.parse_args()
    dd = Path(args.data_dir)
    man = json.load(open(dd / "code_manifest.json"))
    L = []

    def say(s=""):
        print(s)
        L.append(s)

    say("# Code-modelling gates\n")
    say("Generated by `validate_code.py`. Run before training, not after.\n")

    # ---- G1 leakage -------------------------------------------------------
    say("## G1 -- leakage")
    paths = {k: set(v["files"]) for k, v in man.items()}
    ok = True
    for a in paths:
        for b in paths:
            if a < b and paths[a] & paths[b]:
                say(f"- FAIL: {len(paths[a] & paths[b])} shared paths {a}/{b}")
                ok = False
    hashes = {}
    for k, v in man.items():
        hs = set()
        for p in v["files"]:
            try:
                hs.add(hashlib.sha256(open(p, "rb").read()).hexdigest())
            except OSError:
                pass
        hashes[k] = hs
    for a in hashes:
        for b in hashes:
            if a < b and hashes[a] & hashes[b]:
                say(f"- FAIL: {len(hashes[a] & hashes[b])} shared CONTENTS {a}/{b}")
                ok = False
    say(f"- split sizes: " + ", ".join(
        f"{k} {v['bytes']/1048576:.2f} MB / {len(v['files'])} files" for k, v in man.items()))
    say(f"- **{'PASS' if ok else 'FAIL'}**: no file and no file content appears in two splits.\n")

    # ---- G2 annotations ---------------------------------------------------
    say("## G2 -- annotations re-derived from the written bytes")
    g2 = True
    for name in ("val", "test", "train"):
        data, pos, kind, open_pos, depth = load(dd, name)
        bad_c = int((data[pos] != np.array(CLOSER_BYTES)[kind]).sum())
        bad_o = int((data[open_pos] != np.array(OPENER_BYTES)[kind]).sum())
        bad_ord = int((open_pos >= pos).sum())
        bad_d = int((depth < 1).sum())
        say(f"- {name}: {len(pos):,} closers | wrong closer byte {bad_c} | "
            f"wrong opener byte {bad_o} | opener not before closer {bad_ord} | "
            f"depth<1 {bad_d}")
        g2 &= (bad_c == 0 and bad_o == 0 and bad_ord == 0 and bad_d == 0)
    say(f"- **{'PASS' if g2 else 'FAIL'}**: every offset is the bracket it claims to be.\n")

    # ---- G5 chance --------------------------------------------------------
    data, pos, kind, open_pos, depth = load(dd, "val")
    dist = pos - open_pos
    say("## G5 -- chance and the majority class")
    cnt = Counter(kind.tolist())
    tot = len(kind)
    say(f"- uniform over three closers: **0.333**")
    for k, ch in enumerate(")]}"):
        say(f"- marginal `{ch}` : {cnt[k]/tot:.3f}")
    maj = max(cnt.values()) / tot
    say(f"- **majority-class floor: {maj:.3f}** -- a model that always predicts "
        f"`{')]}'[max(cnt, key=cnt.get)]}` scores this. Any headline below it is void.\n")

    # ---- G3 stratum mass --------------------------------------------------
    say("## G3 -- scored positions per stratum (val split)")
    say("Distance is bytes from the matching opener; depth is brackets open at that point.\n")
    grid = np.zeros((len(DEPTH_BINS), len(DIST_BINS)), dtype=np.int64)
    db = np.array([bin_of(int(v), DEPTH_BINS) for v in depth])
    xb = np.array([bin_of(int(v), DIST_BINS) for v in dist])
    for i in range(len(DEPTH_BINS)):
        for j in range(len(DIST_BINS)):
            grid[i, j] = int(((db == i) & (xb == j)).sum())
    hdr = "| depth \\ distance | " + " | ".join(label(DIST_BINS, j) for j in range(len(DIST_BINS))) + " | row % |"
    say(hdr)
    say("|" + "---|" * (len(DIST_BINS) + 2))
    for i in range(len(DEPTH_BINS)):
        row = grid[i]
        say(f"| **{label(DEPTH_BINS, i)}** | " + " | ".join(f"{v:,}" for v in row)
            + f" | {100*row.sum()/tot:.1f}% |")
    say("| **col %** | " + " | ".join(f"{100*grid[:, j].sum()/tot:.1f}%"
                                      for j in range(len(DIST_BINS))) + " | |")
    say("")

    # ---- G4 the no-stack floor -------------------------------------------
    say("## G4 -- the no-stack floor, per stratum")
    say("An n-gram that sees the previous k bytes and predicts which closer comes "
        "next, with backoff. Trained on the train split's closers, scored on val's. "
        "It has NO stack: it cannot know which bracket is open.\n")
    tdata, tpos, tkind, topen, tdepth = load(dd, "train")
    best = {}
    for order in range(1, args.max_order + 1):
        tables = [defaultdict(Counter) for _ in range(order + 1)]
        ctxs = np.stack([tdata[np.clip(tpos - o, 0, None)] for o in range(order, 0, -1)], axis=1)
        for c, k in zip(ctxs, tkind):
            key = tuple(int(x) for x in c)
            for o in range(order, -1, -1):
                tables[o][key[order - o:]][int(k)] += 1
        vctx = np.stack([data[np.clip(pos - o, 0, None)] for o in range(order, 0, -1)], axis=1)
        preds = np.empty(len(pos), dtype=np.int64)
        for i, c in enumerate(vctx):
            key = tuple(int(x) for x in c)
            for o in range(order, -1, -1):
                t = tables[o].get(key[order - o:])
                if t:
                    preds[i] = max(t, key=t.get)
                    break
            else:
                preds[i] = 0
        acc = float((preds == kind).mean())
        best[order] = (acc, preds)
        say(f"- order {order}: overall **{acc:.3f}**")
    bo = max(best, key=lambda o: best[o][0])
    acc, preds = best[bo]
    say(f"\nBest order is **k={bo}** at {acc:.3f} overall. Per stratum:\n")
    say("| depth \\ distance | " + " | ".join(label(DIST_BINS, j) for j in range(len(DIST_BINS))) + " |")
    say("|" + "---|" * (len(DIST_BINS) + 1))
    # The floor of a cell is the BEST predictor that has no stack. Two qualify:
    # the n-gram, and the constant "always )" -- which needs no context at all.
    # They cross: where local context MISLEADS, the n-gram falls below the
    # constant, and quoting the n-gram alone would understate the floor and let
    # a model be read as above-floor when it is not.
    maj_kind = max(cnt, key=cnt.get)
    floors = {}
    for i in range(len(DEPTH_BINS)):
        cells = []
        for j in range(len(DIST_BINS)):
            m = (db == i) & (xb == j)
            if m.sum() < 200:
                cells.append("--")
                continue
            f_ng = float((preds[m] == kind[m]).mean())
            f_const = float((kind[m] == maj_kind).mean())
            f = max(f_ng, f_const)
            floors[f"d{label(DEPTH_BINS,i)}/x{label(DIST_BINS,j)}"] = f
            mark = "n" if f_ng >= f_const else "c"
            cells.append(f"{f:.3f}{mark}")
        say(f"| **{label(DEPTH_BINS, i)}** | " + " | ".join(cells) + " |")
    say("")
    say("Suffix `n` = the n-gram is the stronger no-stack predictor in that cell, "
        "`c` = the constant `)` is. Where `c` wins, local context actively misleads.\n")
    if floors:
        worst = min(floors, key=floors.get)
        say(f"- Lowest floor cell: **{worst} = {floors[worst]:.3f}** -- this is where a "
            f"stack can show, and the only place a headline means anything.")
        hi = sum(1 for v in floors.values() if v > 0.95)
        say(f"- Cells where the no-stack floor is already above 0.95: **{hi} of {len(floors)}**.")
    say("")
    json.dump({"majority": maj, "ngram_overall": acc, "ngram_order": bo,
               "floors": floors, "g1_pass": ok, "g2_pass": g2},
              open(os.path.join(_REPO, "CODE_GATES.json"), "w"), indent=2)
    Path(args.out).write_text("\n".join(L) + "\n")
    print(f"\nwrote {args.out} and CODE_GATES.json")
    if not (ok and g2):
        raise SystemExit("GATE FAILURE -- do not train on this corpus")


if __name__ == "__main__":
    main()
