"""Render e0_results.json (+ e0_step_geometry.json) as e0_table.md. Conditions with 3 draws (ROT, RANDMAP*, SPARSE)
are shown as the mean over draws with [min, max]. Run: python3 /home/prashr/mapformer/docs/audits/2026-10-03/e0_table.py"""
import json
from pathlib import Path

D = Path("/home/prashr/mapformer/docs/audits/2026-10-03")
R = json.load(open(D / "e0_results.json"))
G = json.load(open(D / "e0_step_geometry.json"))
PATH = ["MapWM", "MapPoPE", "MapEM", "PosOnly"]
INDEX = ["RoPE", "PoPE"]
ROWS = [("ID", ["ID"]), ("ROT (control)", ["ROT_0", "ROT_1", "ROT_2"]),
        ("NORMEMB x0.5", ["NORMEMB_x0.5"]), ("NORMEMB x2", ["NORMEMB_x2"]), ("NORMEMB x4", ["NORMEMB_x4"]),
        ("NORMEMB x8", ["NORMEMB_x8"]),
        ("RANDMAP s0.5", [f"RANDMAP_s0.5_{d}" for d in range(3)]),
        ("RANDMAP s1", [f"RANDMAP_s1_{d}" for d in range(3)]),
        ("RANDMAP s2", [f"RANDMAP_s2_{d}" for d in range(3)]),
        ("RANDMAP norm-matched", [f"RANDMAPnm_{d}" for d in range(3)]),
        ("SPARSE k=8", [f"SPARSE_{d}" for d in range(3)]),
        ("PROJIN (step row space)", ["PROJIN"]), ("PROJOUT (complement)", ["PROJOUT"])]


def get(arm, pool, cond, f):
    return f(R["results"][arm][f"{pool}|{cond}"])


def cell(arm, pool, conds, f, fmt="{:.4f}", sign=False):
    v = [get(arm, pool, c, f) for c in conds]
    m = sum(v) / len(v)
    s = ("{:+.4f}" if sign else fmt).format(m)
    if len(v) > 1:
        lo, hi = min(v), max(v)
        s += (" [{:+.3f},{:+.3f}]" if sign else " [{:.3f},{:.3f}]").format(lo, hi)
    return s


o_i = lambda r: r["intact"]["obj_acc"]
o_zo = lambda r: r["zobj"]["obj_acc"]
o_zb = lambda r: r["zob"]["obj_acc"]
L_obj = lambda r: r["zobj"]["obj_acc"] - r["intact"]["obj_acc"]
L_reg = lambda r: r["L"]
gain = lambda r: r["intact"]["gain_obj"]
auc_i = lambda r: r["intact"]["blank_auc"]
auc_zo = lambda r: r["zobj"]["blank_auc"]
all_i = lambda r: r["intact"]["all_acc"]
all_zo = lambda r: r["zobj"]["all_acc"]

out = []
w = out.append
fl = R["floors"]
w("# E0 leak decomposition: tables (generated by e0_table.py from e0_results.json)\n")
w(f"200 sequences per pool (env seed 10000, np seed 10**6, train_newobj.evaluate's stream), T=1024 steps, "
  f"{R['results']['MapWM']['test|ID']['intact']['n_obj_targets']} object revisit targets and "
  f"{R['results']['MapWM']['test|ID']['intact']['n_targets']} revisit targets per pool. n=1 seed per arm.\n")
w(f"Floors (test pool): always-blank all-target accuracy {fl['test']['always_blank_all_acc']:.4f}; object identity: "
  f"chance over the pool 0.001, a uniform guess among the 16 in-sequence objects 0.0625.\n")
w("Columns. intact: object-identity accuracy (argmax over the active pool's objects, revisit targets that are "
  "objects). zobj: object-token steps zeroed. zob: object and blank steps zeroed (the brief's C). "
  "L_obj = zobj - intact. L_reg = zob - intact (the brief's L). gain: RMS object step / RMS action step "
  "(intact). AUC: blank-detection AUC, intact. all: legacy all-target accuracy, intact. "
  "3-draw conditions: mean [min, max].\n")
w("NORMBOTH gives object-identity numbers identical to NORMEMB in every arm (readout scale cannot move an argmax "
  "among objects); it differs only in AUC/all (second table).\n")
for arm in PATH:
    w(f"\n## {arm} (test pool)\n")
    w("| condition | intact | zobj | zob (C) | L_obj | L_reg | gain | AUC | all |")
    w("|---|---|---|---|---|---|---|---|---|")
    for name, cs in ROWS:
        w(f"| {name} | {cell(arm,'test',cs,o_i)} | {cell(arm,'test',cs,o_zo)} | {cell(arm,'test',cs,o_zb)} | "
          f"{cell(arm,'test',cs,L_obj,sign=True)} | {cell(arm,'test',cs,L_reg,sign=True)} | "
          f"{cell(arm,'test',cs,gain)} | {cell(arm,'test',cs,auc_i)} | {cell(arm,'test',cs,all_i)} |")
    cs = ["ID"]
    w(f"| train pool, ID | {cell(arm,'train',cs,o_i)} | {cell(arm,'train',cs,o_zo)} | {cell(arm,'train',cs,o_zb)} | "
      f"{cell(arm,'train',cs,L_obj,sign=True)} | {cell(arm,'train',cs,L_reg,sign=True)} | "
      f"{cell(arm,'train',cs,gain)} | {cell(arm,'train',cs,auc_i)} | {cell(arm,'train',cs,all_i)} |")
    se = R["results"][arm]["test|ID"]["L_se_eval"]
    w(f"\nEval-sample SE of L_reg at ID (sequence-clustered): {se:.4f}. Not seed noise.")

w("\n## Readout-side scale: NORMEMB vs NORMBOTH (test pool; blank AUC and all-target, intact / zobj)\n")
w("| arm | s | EMB AUC | BOTH AUC | EMB all | BOTH all | BOTH all, zobj |")
w("|---|---|---|---|---|---|---|")
for arm in PATH + INDEX:
    for s in ("0.5", "2", "4", "8"):
        e, b = f"NORMEMB_x{s}", f"NORMBOTH_x{s}"
        zo = cell(arm, 'test', [b], all_zo) if arm in PATH else "n/a"
        w(f"| {arm} | {s} | {cell(arm,'test',[e],auc_i)} | {cell(arm,'test',[b],auc_i)} | "
          f"{cell(arm,'test',[e],all_i)} | {cell(arm,'test',[b],all_i)} | {zo} |")

w("\n## Index arms (no step: structural null; they fail the task on both pools)\n")
w("| arm | condition | obj intact | AUC | all |")
w("|---|---|---|---|---|")
for arm in INDEX:
    for pool in ("train", "test"):
        w(f"| {arm} | {pool} ID | {cell(arm,pool,['ID'],o_i)} | {cell(arm,pool,['ID'],auc_i)} | {cell(arm,pool,['ID'],all_i)} |")
    for name, cs in ROWS[1:11]:
        w(f"| {arm} | test {name} | {cell(arm,'test',cs,o_i)} | {cell(arm,'test',cs,auc_i)} | {cell(arm,'test',cs,all_i)} |")

w("\n## Step geometry (angle units, omega * delta; e0_step_geometry.json)\n")
w("r_x = a(+x) + a(-x), r_y likewise (exact path integration needs 0); b = blank step.\n")
w("| arm | abs(r_x)/abs(a) | abs(r_y)/abs(a) | abs(b)/abs(a) | cos(b, r_x) | cos(b, r_y) | RMS obj/abs(a) | abs(mean obj)/abs(a) |")
w("|---|---|---|---|---|---|---|---|")
for arm in PATH:
    g = G[arm]["angle"]
    w(f"| {arm} | {g['|r_x|/|a|']:.4f} | {g['|r_y|/|a|']:.4f} | {g['|b|/|a|']:.4f} | {g['cos(b,r_x)']:+.3f} | "
      f"{g['cos(b,r_y)']:+.3f} | {g['rms_obj/|a|']:.4f} | {g['|mean_obj|/|a|']:.5f} |")
w("\nObject-step map M = W_out W_in A (H*nb x 64) singular values (rank 4 = W_in's rank):\n")
for arm in PATH:
    sv = R["step_map"][arm]["singular_values_top8"][:5]
    w(f"- {arm}: " + ", ".join(f"{x:.2e}" for x in sv))

w("\n## Verification (rule 9), per arm\n")
for arm, v in R["verify"].items():
    w(f"- {arm}: " + "; ".join(f"{k}={v[k]}" for k in v))
(D / "e0_table.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
